//! The corpus, posed to an e-graph.
//!
//! `prove` searches with a tactic. This writes the same question down in
//! [egglog]'s language instead — the equations as rewrite rules, the identities
//! as two terms and a `check` — so that saturation can be asked whether the two
//! sides meet. Nothing here reads an answer back; what comes out is a file to
//! run, and `docs/egglog.md` is the design it is a first cut of.
//!
//! **This is a producer of a question, not of a proof.** Whatever an e-graph
//! concludes has to come back as a `.hand` derivation and be replayed before it
//! means anything, so nothing in this module is on the path that decides an
//! identity. That is why it may be approximate where [`crate::rule`] may not.
//!
//! [egglog]: https://github.com/egraphs-good/egglog
//!
//! ## What is approximate, and why that is allowed
//!
//! - **A value is opaque.** `Val` holds the literal's `.hand` spelling and
//!   nothing else, so two values are equal exactly when they are written the
//!   same. That is right for every literal the format can spell, and it costs
//!   `eval`, which would have to compute on one. `eval` is not emitted.
//! - **Provenance is dropped**, as it is on the wire and in
//!   [`crate::ir::same_effect`]. An e-graph's whole business is merging terms
//!   that are equal, and origins would keep two identical blocks apart.
//! - **Several equations are emitted in one direction only**, because the other
//!   reading has a variable the pattern does not bind — `counit` backward has to
//!   invent a `d` — or because it can fire on its own output forever. Each one
//!   says which, beside it in the generated file.
//! - **The laws with a repetition count** — `drop^m`, `(roll d)^(d+1)` — have no
//!   single pattern, so they are emitted instantiated at every width up to a
//!   bound.
//!
//! ## A sequence is a cons list
//!
//! The choice that decides everything else. A monoid — `Cat`, associativity as
//! a rewrite — is the obvious encoding of a concatenative language and it is a
//! trap: every re-association of a term is a distinct e-node, and a window will
//! not match until they all exist. A cons list gives a sequence exactly one
//! spelling, so a window matches where it sits.
//!
//! What that costs is concatenation, which five laws need. It is bought back
//! with an `app` constructor and two reduction rules, and the reason it is not
//! associativity in disguise is that **no pattern here contains an `app`**: it
//! is built on right-hand sides and reduced away, never searched for.
//!
//! A law that wants a *whole subsequence* — `annihilate`, `interchange` — takes
//! a single [`Node`] instead, because a `dip 0` frame is a subsequence wearing
//! one node's clothes. Packaging a window is then a derivation in the calculus
//! — frame, `fuse`, apply, unframe — rather than a rule that spans the spine.
//! [`Node::Call`] is the same idea already in the language, which is why
//! unfolding is stated as `(Call k S) = (Dip k body)` and needs no splicing.

use std::collections::{BTreeSet, HashSet};
use std::fmt::Write as _;

use bytecode::arity::op_arity;
use bytecode::{Instruction, SentenceIndex};

use crate::ir::{self, Node};
use crate::program::Program;
use crate::serial;

/// One identity, as the emitter needs it: a name and its two sides.
pub(crate) struct Posed {
    pub(crate) name: String,
    pub(crate) lhs: SentenceIndex,
    pub(crate) rhs: SentenceIndex,
}

/// How wide the instantiated laws are spelled out.
///
/// `annihilate` and `roll_cycle` are stated with a repetition count, which a
/// pattern cannot hold, so each is emitted once per width. Three is enough for
/// every arity in the corpus and keeps the rule count in two figures.
pub(crate) const DEFAULT_BOUND: i64 = 3;

/// The whole file: sorts, facts, equations, the corpus, and the checks.
pub(crate) fn emit(prog: &Program, posed: &[Posed], bound: i64) -> Result<String, String> {
    let mut out = String::new();

    header(&mut out, posed, bound);
    sorts(&mut out);
    facts(&mut out)?;
    arity_rules(&mut out);
    splice(&mut out);
    laws(&mut out, bound);
    roll_laws(&mut out, bound);

    let sentences = reachable(prog, posed);
    unfolding(&mut out, prog, &sentences)?;
    corpus(&mut out, prog, posed)?;
    notes(&mut out);

    Ok(out)
}

// ---------------------------------------------------------------------------
// The file, section by section
// ---------------------------------------------------------------------------

fn header(out: &mut String, posed: &[Posed], bound: i64) {
    let _ = write!(
        out,
        r#";; Generated by `prove --emit-egglog`. Do not edit; regenerate.
;;
;; {} identit{}, posed to an e-graph. Run it with:
;;
;;     egglog this-file.egg
;;
;; `check` aborts the run at the first claim that does not close, so the checks
;; are listed one per line at the bottom and the fastest way to look at one
;; identity is to emit it alone:
;;
;;     prove <dir> --emit-egglog one.egg --filter <name>
;;
;; Instantiated laws are spelled out to width {}; `--egglog-bound` moves that.
;;
;; The equations are `docs/tactics.md`; the design this is a first cut of is
;; `docs/egglog.md`. What is NOT emitted, and why:
;;
;;   eval          needs to compute on a literal, and a literal is opaque here
;;   unframe       stated with a repetition count on both sides at once
;;   copy_nat      the same, and it is the law worth reaching for next
;;   annihilate    emitted for m in 0..=2 — the void, unflagged and flagged
;;                 readings. `node-arity` is what makes m = 0 affordable: the
;;                 pattern is a bare `Cons`, and the arity fact is the guard
;;   distribute    forward only; backward means splitting a cons list at a
;;                 point nothing names
;;
;; and the readings that are emitted forward only, each marked below:
;; `collapse`, `elim_dip0`, `fuse`, `distribute`, `fold_branch`, `commute`,
;; `split_bool`, `counit`, `counit_under`, `retest`, `cancel_tuple`,
;; `annihilate`.
;;
;; `elim_dip0` backward is the exception, in the `framing` ruleset: it invents a
;; frame, which nothing bounds, so it is *aimed* at the one place the next step
;; can use it — the head of two branch arms that already agree.

"#,
        posed.len(),
        if posed.len() == 1 { "y" } else { "ies" },
        bound,
    );
}

fn sorts(out: &mut String) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Sorts
;; ---------------------------------------------------------------------------

;; A literal by its `.hand` spelling, which is injective for every value the
;; format can write: `9`, `true`, `"text"`, `1.5`, `(1, 2)`, `mod::sym`.
(datatype Val (Lit String))

;; The instructions an equation looks *inside* get a shape; the rest are named.
;; `panic`, `assert` and `assert_eq` have no spelling here for the same reason
;; they have none on the wire: every equation is stated about code that cannot
;; fail.
(datatype Instr
  (Push Val)
  (Drop)
  (Pick i64)
  (Roll i64)
  (Tuple i64)
  (Untuple i64)
  (Prim String))

;; A term is a sequence of nodes, and a sequence is a **cons list**. Not a
;; monoid: with `Cat` every re-association of a term is a distinct e-node and
;; every window needs associativity saturated before it will match, which is
;; where equality saturation goes to die. A cons list gives every suffix exactly
;; one representation, so a fixed-width window matches with no normalization at
;; all.
;;
;; A `Call` names its sentence, never an index: an index is an offset into one
;; assembly of one corpus.
(datatype*
  (Node
    (Op Instr)
    (Call i64 String)
    (Dip i64 Seq)
    (Branch Seq Seq))
  (Seq
    (Empty)
    (Cons Node Seq)))

;; Concatenation, which a cons list does not have for free.
;;
;; **It is only ever built, never matched.** Five laws construct a concatenation
;; on their right-hand side — `elim_dip0`, `fuse`, `distribute`, `fold_branch`,
;; `retest` — and no law's pattern contains an `app`. That is the whole
;; difference from associativity: these two rules *reduce*, deterministically,
;; down the spine of a list that is already built, where a `Cat` birewrite
;; searches. So concatenation costs a linear rewrite and buys no combinatorics.
;;
;; A reading that would have to *match* one is a reading this encoding does not
;; have: `distribute` backward factors a shared suffix out of two arms, and
;; finding it means splitting a cons list at a point nothing names.
(constructor app (Seq Seq) Seq)

"#,
    );
}

fn facts(out: &mut String) -> Result<(), String> {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Facts the search cannot re-derive
;; ---------------------------------------------------------------------------

;; The applier re-derives every fact a step rests on, against the real library.
;; A searcher in another process has no library, so the facts are dumped here —
;; and a wrong table costs a rejected derivation, never a wrong proof, because
;; `Rule::check` asks again when the step is applied.
;;
;; `commutative` and `yields-bool` are swept against the interpreter over every
;; operand shape, so what is copied here is a measured fact rather than a
;; comment.

;; Its own ruleset, saturated before every round of laws: an arity is a fact
;; about a term, so it has to be settled before a law that reads one can fire.
(ruleset analysis)

(relation commutative (Instr))
(relation yields-bool (Instr))

;; `untuple n` leaves a flag like the others, but it carries an operand, so it
;; is shaped rather than named and cannot be a row.
(rule ((= i (Untuple k))) ((yields-bool i)) :ruleset analysis)

"#,
    );

    for inst in primitives() {
        let name = format!("{}", inst);
        if inst.commutative() {
            let _ = writeln!(out, "(commutative (Prim \"{}\"))", name);
        }
    }
    out.push('\n');
    for inst in primitives() {
        let name = format!("{}", inst);
        if inst.yields_bool() {
            let _ = writeln!(out, "(yields-bool (Prim \"{}\"))", name);
        }
    }

    out.push_str(
        r#"
;; Arity, as a lattice rather than a number.
;;
;; It is NOT an e-class invariant: `pick 1 ; drop` is (2 -> 2) where nothing is
;; (0 -> 0), which is why an identity is held to its net change rather than to
;; its full arity. What is invariant is the net; the input requirement is an
;; upper bound that falls when two terms are found equal. So `min` on the one
;; and `:no-merge` on the other, which is exactly what the two mean.
;;
;; A rule firing on a joined-down bound is still sound: everything in a class is
;; equal, so a law true of the member with the lower requirement is true of the
;; class. What is *not* sound is writing that number into a derivation — the
;; step's arguments have to be recomputed from the concrete term. See
;; `docs/egglog.md`.

;; Arity is a *relation*, and it is upward closed: anything of arity (n, m) is
;; also of arity (n+1, m+1), because a program that ignores what is under it
;; ignores one more just as happily. So a term carries a set of arities rather
;; than a number, two terms in a class simply contribute their facts to the same
;; set, and there is nothing to merge and nothing to conflict.
(relation instr-arity (Instr i64 i64))
(relation node-arity (Node i64 i64))
(relation seq-arity (Seq i64 i64))

;; The primitive instructions, from `bytecode::arity::op_arity`.
(relation prim-arity (String i64 i64))
"#,
    );

    for inst in primitives() {
        let name = format!("{}", inst);
        let (n, m) = op_arity(&inst)
            .ok_or_else(|| format!("`{}` has no arity, which should not happen", name))?;
        let _ = writeln!(out, "(prim-arity \"{}\" {} {})", name, n, m);
    }

    out.push('\n');
    Ok(())
}

fn arity_rules(out: &mut String) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Arity, computed bottom-up
;; ---------------------------------------------------------------------------

;; `pick d` is (d+1 -> d+2), `roll d` is (d+1 -> d+1), `tuple n` is (n -> 1),
;; `untuple n` is (1 -> n+1) — the parametric ones are rules rather than rows.
(rule ((= i (Push c)))    ((instr-arity i 0 1)) :ruleset analysis)
(rule ((= i (Drop)))      ((instr-arity i 1 0)) :ruleset analysis)
(rule ((= i (Pick d)))    ((instr-arity i (+ d 1) (+ d 2))) :ruleset analysis)
(rule ((= i (Roll d)))    ((instr-arity i (+ d 1) (+ d 1))) :ruleset analysis)
(rule ((= i (Tuple k)))   ((instr-arity i k 1)) :ruleset analysis)
(rule ((= i (Untuple k))) ((instr-arity i 1 (+ k 1))) :ruleset analysis)
(rule ((= i (Prim p)) (prim-arity p n m)) ((instr-arity i n m)) :ruleset analysis)

(rule ((= x (Op i)) (instr-arity i n m)) ((node-arity x n m)) :ruleset analysis)

;; A frame adds its depth to both ends and changes nothing else.
(rule ((= x (Dip k b)) (seq-arity b n m))
      ((node-arity x (+ k n) (+ k m))) :ruleset analysis)

;; A branch pops the condition, then runs an arm. Both arms have to be measured
;; at the same level, which is what the closure below is for.
(rule ((= x (Branch t e)) (seq-arity t n m) (seq-arity e n m))
      ((node-arity x (+ n 1) m)) :ruleset analysis)

(rule ((= s (Empty))) ((seq-arity s 0 0)) :ruleset analysis)

;; Composition: the head leaves what the tail takes. The middle has to line up
;; exactly, and lifting is how it comes to.
(rule ((= s (Cons n r)) (node-arity n a b) (seq-arity r b d))
      ((seq-arity s a d)) :ruleset analysis)
(rule ((= s (app a b)) (seq-arity a n k) (seq-arity b k m))
      ((seq-arity s n m)) :ruleset analysis)

"#,
    );

    let _ = write!(
        out,
        r#";; The closure, bounded. Unbounded it is an infinite set of facts; the bound
;; is how deep a stack any of this reasons about, and it has to be at least as
;; deep as the widest middle a composition has to line up on.
(rule ((instr-arity i n m) (< n {lift})) ((instr-arity i (+ n 1) (+ m 1))) :ruleset analysis)
(rule ((node-arity x n m) (< n {lift})) ((node-arity x (+ n 1) (+ m 1))) :ruleset analysis)
(rule ((seq-arity s n m) (< n {lift})) ((seq-arity s (+ n 1) (+ m 1))) :ruleset analysis)

"#,
        lift = LIFT
    );
}

/// How far arity facts are lifted.
///
/// Composition needs the head's outputs and the tail's inputs to be the same
/// number, and lifting is what makes them meet — so this has to clear the
/// deepest stack any window in the corpus stands on, not the widest law.
const LIFT: i64 = 6;

fn splice(out: &mut String) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Reducing a concatenation
;; ---------------------------------------------------------------------------

;; Bookkeeping, not laws. Two `Seq` terms that differ only by how a
;; concatenation was spelled are the same `Vec<Node>`, so a translator reading a
;; proof out of here drops these steps rather than writing them down.
;;
;; Saturated every round, and cheap: an application walks one cons cell, and a
;; list is finite. This is the whole of what associativity was for, done by
;; reduction instead of by search.
(ruleset splice)
(rewrite (app (Empty) b) b :ruleset splice)
(rewrite (app (Cons n a) b) (Cons n (app a b)) :ruleset splice)

"#,
    );
}

/// The equations of `docs/tactics.md`, in whichever readings a pattern can hold.
fn laws(out: &mut String, bound: i64) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; The equations
;; ---------------------------------------------------------------------------

(ruleset laws)

;; collapse: dip k { dip j { A } } = dip (k+j) { A }
;; `A` is a whole Dip body, which is a field rather than a span of the spine, so
;; a cons list binds it with no trouble. Forward only: k+j does not say which k
;; and which j.
(rule ((= n (Dip k (Cons (Dip j a) (Empty)))))
      ((union n (Dip (+ k j) a)))
      :ruleset laws)

;; elim_dip0: dip 0 { A } = A
;; The first place concatenation is needed, and it is needed only on the right.
;; Forward only here; the backward reading is the framing ruleset below.
(rewrite (Cons (Dip 0 a) rest) (app a rest) :ruleset laws)

;; interchange: X ; D_k = D_(k-m+n) ; X, for X : n -> m, k >= m
;; X is one node, which under a cons list is what a spine variable *is*. A
;; multi-node X is a `dip 0` frame, which is also one node — so this covers both
;; without a second rule, and the packaging is a derivation rather than a case.
(rule ((= s (Cons x (Cons (Dip k b) rest))) (node-arity x n m) (>= k m))
      ((union s (Cons (Dip (+ (- k m) n) b) (Cons x rest))))
      :ruleset laws)
(rule ((= s (Cons (Dip k b) (Cons x rest))) (node-arity x n m) (>= k n))
      ((union s (Cons x (Cons (Dip (+ (- k n) m) b) rest))))
      :ruleset laws)

;; fuse: dip k { A } ; dip k { B } = dip k { A B }
;; Forward only: read backward the split point is free. At k = 0 this is what
;; turns two framed nodes into one framed pair, which is how a multi-node window
;; gets packaged for the laws that want a single X.
(rewrite (Cons (Dip k a) (Cons (Dip k b) rest))
         (Cons (Dip k (app a b)) rest)
         :ruleset laws)

;; hoist: dip (k+1) { X } ; branch { A } { B }
;;      = branch { dip k { X } ; A } { dip k { X } ; B }
;; Both readings, and neither needs `app`: the arms are fields, and the frame is
;; consed onto the front of each.
(rule ((= s (Cons (Dip k x) (Cons (Branch a b) rest))) (> k 0))
      ((union s (Cons (Branch (Cons (Dip (- k 1) x) a)
                              (Cons (Dip (- k 1) x) b)) rest)))
      :ruleset laws)
(rule ((= s (Cons (Branch (Cons (Dip k x) a) (Cons (Dip k x) b)) rest)))
      ((union s (Cons (Dip (+ k 1) x) (Cons (Branch a b) rest))))
      :ruleset laws)

;; distribute: branch { A } { B } ; C = branch { A C } { B C }
;; Forward only. Backward factors a shared suffix out of two arms, which means
;; splitting a cons list at a point nothing names — the one reading a monoid
;; would have bought, and the price of it was the whole e-graph.
;; The guard is not decoration: without it the rule matches its own output with
;; `c = (Empty)` and distributes nothing into the arms, forever.
(rule ((= s (Cons (Branch a b) c)) (!= c (Empty)))
      ((union s (Cons (Branch (app a c) (app b c)) (Empty))))
      :ruleset laws)

;; fold_branch: push c ; branch { A } { B } = the arm c selects
;; Selected by truthiness, and `false` is the only falsy value — so `push 1`
;; takes the *then* arm, as firmly as `push false` takes the else arm.
;; Forward only: an arm does not say what condition chose it.
(rule ((= s (Cons (Op (Push c)) (Cons (Branch a b) rest))) (!= c (Lit "false")))
      ((union s (app a rest)))
      :ruleset laws)
(rule ((= s (Cons (Op (Push (Lit "false"))) (Cons (Branch a b) rest))))
      ((union s (app b rest)))
      :ruleset laws)

;; commute: roll 1 ; op = op, for a commutative op
;; Forward only: read backward it prepends a `roll 1` forever.
(rule ((= s (Cons (Op (Roll 1)) (Cons (Op o) rest))) (commutative o))
      ((union s (Cons (Op o) rest)))
      :ruleset laws)

;; split_bool: pick 0 ; is_bool ; branch { branch { push true } { push false } } { }
;;           = nothing
;; Forward only: backward is a case split, which needs somewhere to stand.
(rewrite (Cons (Op (Pick 0))
               (Cons (Op (Prim "is_bool"))
                     (Cons (Branch (Cons (Branch (Cons (Op (Push (Lit "true"))) (Empty))
                                                 (Cons (Op (Push (Lit "false"))) (Empty)))
                                         (Empty))
                                   (Empty))
                           rest)))
         rest
         :ruleset laws)

;; counit: pick d ; drop = nothing            (copy, discard the copy)
;; counit_under: pick 0 ; dip 1 { drop } = nothing   (discard the original)
;; Forward only: backward has to invent a `d`, and then another.
(rewrite (Cons (Op (Pick d)) (Cons (Op (Drop)) rest)) rest :ruleset laws)
(rewrite (Cons (Op (Pick 0)) (Cons (Dip 1 (Cons (Op (Drop)) (Empty))) rest)) rest
         :ruleset laws)

;; retest: pick 0 ; branch { branch { A } { B } ; R } { Q }
;;       = pick 0 ; branch { drop ; A ; R } { Q },  and the mirror
;; The same value tested twice answers the same, so the other inner arm is dead.
;; Forward only: the dead arm is not recoverable from the collapsed one.
(rule ((= s (Cons (Op (Pick 0))
                  (Cons (Branch (Cons (Branch a b) r) q) rest))))
      ((union s (Cons (Op (Pick 0))
                      (Cons (Branch (Cons (Op (Drop)) (app a r)) q) rest))))
      :ruleset laws)
(rule ((= s (Cons (Op (Pick 0))
                  (Cons (Branch q (Cons (Branch a b) r)) rest))))
      ((union s (Cons (Op (Pick 0))
                      (Cons (Branch q (Cons (Op (Drop)) (app b r))) rest))))
      :ruleset laws)

;; copy_const: push c ; pick 0 = push c ; push c
(birewrite (Cons (Op (Push c)) (Cons (Op (Pick 0)) rest))
           (Cons (Op (Push c)) (Cons (Op (Push c)) rest))
           :ruleset laws)

;; copy_assoc: pick d ; pick 0 = pick d ; dip 1 { pick d }
;; Neither side is smaller; the point is that one copy ends up in a frame.
(birewrite (Cons (Op (Pick d)) (Cons (Op (Pick 0)) rest))
           (Cons (Op (Pick d)) (Cons (Dip 1 (Cons (Op (Pick d)) (Empty))) rest))
           :ruleset laws)

;; bool_result: op ; is_bool = op ; drop ; push true, for an op yielding a bool
;; The only fact here about an instruction's codomain, and the only one no
;; rewriting could reach.
(rule ((= s (Cons (Op o) (Cons (Op (Prim "is_bool")) rest))) (yields-bool o))
      ((union s (Cons (Op o)
                      (Cons (Op (Drop))
                            (Cons (Op (Push (Lit "true"))) rest)))))
      :ruleset laws)
(rule ((= s (Cons (Op o)
                  (Cons (Op (Drop))
                        (Cons (Op (Push (Lit "true"))) rest))))
       (yields-bool o))
      ((union s (Cons (Op o) (Cons (Op (Prim "is_bool")) rest))))
      :ruleset laws)

;; cancel_tuple: tuple n ; untuple n = push true
;; Forward only: `push true` does not say which n. The converse order is not a
;; no-op and has no equation.
(rewrite (Cons (Op (Tuple n)) (Cons (Op (Untuple n)) rest))
         (Cons (Op (Push (Lit "true"))) rest)
         :ruleset laws)

"#,
    );

    annihilate(out, bound);
}

/// `X ; drop^m` = `drop^n`, one rule per `(n, m)` up to the bound.
///
/// The count is on both sides and a pattern cannot hold one, so the law is
/// spelled out. `m = 0` has a bare `Cons` for a pattern — every non-empty
/// sequence in the file — and is affordable only because `node-arity` is a
/// relation: the arity fact does the constraining the pattern cannot.
///
/// `X` is a single [`Node`], which under a cons list is what a spine variable
/// is. It reaches a multi-node `X` through the packaging the framing ruleset
/// starts and `fuse` finishes, rather than through a rule that spans the spine.
fn annihilate(out: &mut String, bound: i64) {
    out.push_str(
        r#";; annihilate: X ; drop^m = drop^n, for X : n -> m
;; The workhorse, and the one law stated with a repetition count — so it is
;; spelled out once per width. Forward only: read backward it introduces an X
;; the pattern cannot name, which is `introduce`, and which is exactly the step
;; a search here cannot take. Widths below are m in 1..=2, n in 0..=bound.
;;
;; `x` is one node. A multi-node X is a `dip 0` frame, which is also one node,
;; so this rule reaches both — see the framing ruleset.
"#,
    );
    for m in 0..=2i64 {
        for n in 0..=bound {
            let _ = writeln!(
                out,
                "(rule ((= s (Cons x {})) (node-arity x {} {}))\n      \
                 ((union s {}))\n      :ruleset laws)",
                drops(m, "rest"),
                n,
                m,
                drops(n, "rest"),
            );
        }
    }
    out.push('\n');
}

/// `drop` repeated `k` times in front of `tail`, as a `Seq` expression.
fn drops(k: i64, tail: &str) -> String {
    let mut s = tail.to_string();
    for _ in 0..k {
        s = format!("(Cons (Op (Drop)) {})", s);
    }
    s
}

/// `roll d` repeated `k` times in front of `tail`.
fn rolls(d: i64, k: i64, tail: &str) -> String {
    let mut s = tail.to_string();
    for _ in 0..k {
        s = format!("(Cons (Op (Roll {})) {})", d, s);
    }
    s
}

fn roll_laws(out: &mut String, bound: i64) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; The one generative reading that is emitted
;; ---------------------------------------------------------------------------

;; elim_dip0 backward, twice, at the head of each arm of a branch. Read forward
;; the equation splices; read backward it *introduces* a frame, and introducing
;; is how factoring starts — a shared prefix has to be in a frame before `hoist`
;; can lift it out of two arms.
;;
;; Every other backward reading that invents material is left out, because it
;; never stops. This one is emitted because it can be **aimed**: it fires only
;; where both arms already begin with the same node, which is exactly the
;; precondition of the step that consumes it. That is not a new axiom — it is
;; two instances of `elim_dip0` at named positions, which is what a matcher is —
;; and it is the difference between a rule that generates and a rule that
;; generates *somewhere useful*.
;;
;; Aiming is not a nicety here. The unaimed version — frame the head of every
;; sequence — wraps every cons cell, `elim_dip0` unwraps each one back through
;; `app`, and `discarded_work_on_copies` stops finishing at all. This one costs
;; nothing measurable and `a_value_tested_twice`, which does not close without
;; it, proves in about thirty milliseconds.
(ruleset framing)
(rule ((= n (Branch (Cons h a) (Cons h b))))
      ((union n (Branch (Cons (Dip 0 (Cons h (Empty))) a)
                        (Cons (Dip 0 (Cons h (Empty))) b))))
      :ruleset framing)

;; ---------------------------------------------------------------------------
;; The roll laws, which nothing places yet
;; ---------------------------------------------------------------------------

;; `roll_cycle`, `pick_roll` and `unframe` are equations a script may name, but
;; no matcher looks for any of them — what each reading should search for is an
;; open question. A pattern is not a matcher, so two of the three arrive here
;; for free.
;;
;; Their own ruleset because `pick_roll` forward fires on every `pick` and grows
;; the term every time. Add `(run rolls)` to the schedule to turn them on.
(ruleset rolls)

;; pick_roll: pick d = dip d { pick 0 } ; roll d
(birewrite (Cons (Op (Pick d)) rest)
           (Cons (Dip d (Cons (Op (Pick 0)) (Empty))) (Cons (Op (Roll d)) rest))
           :ruleset rolls)

;; roll_cycle: (roll d)^(d+1) = nothing. A rotation of d+1 things has order d+1.
;; Forward only, and instantiated: the count is the law.
"#,
    );
    for d in 0..=bound {
        let _ = writeln!(
            out,
            "(rewrite {} rest :ruleset rolls)",
            rolls(d, d + 1, "rest")
        );
    }
    out.push_str(
        "\n;; unframe is not emitted: dip d { X } ; (roll (d+m-1))^m = (roll (d+n-1))^n ; X\n\
         ;; has a repetition count on *both* sides at once, driven by an arity the\n\
         ;; pattern would also have to read. It wants the same treatment as\n\
         ;; annihilate, one rule per (d, n, m), which is a cube rather than a square.\n\n",
    );
}

fn unfolding(
    out: &mut String,
    prog: &Program,
    sentences: &BTreeSet<SentenceIndex>,
) -> Result<(), String> {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; What the library says
;; ---------------------------------------------------------------------------

;; That `Call { k, S }` may be replaced by S's body is not a law of the calculus
;; — it is the axiom the library contributes by defining S, and it says nothing
;; about any other sentence. So it is one birewrite per sentence rather than a
;; rule, and only for the sentences the identities can reach.
;;
;; It is stated at the **node** level, `(Call k S) = (Dip k body)`, which is one
;; rule for every depth at once and needs no concatenation. That is not a trick:
;; `ir::frame_depth` already treats a call and a dip as the same thing wearing
;; different clothes, differing only in whether the body is written out. Getting
;; from `(Dip 0 body)` into the enclosing sequence is then `elim_dip0`, an
;; equation, rather than something the unfolding rule does on the side.
;;
;; Read backward it folds, which `docs/identities.md` calls the real gap because
;; nothing can read a window and say which sentence to fold into. Congruence
;; does not have that problem: the body is in a class and so is the call.
(ruleset unfold)

"#,
    );

    for &target in sentences {
        let name = serial::sentence_name(prog, target)?;
        let body = ir::build(prog.library(), target, &mut HashSet::new());
        let _ = writeln!(
            out,
            "(let ${} {})",
            global(&name),
            seq(prog, &body)?
        );
        let _ = writeln!(
            out,
            "(birewrite (Call k \"{}\") (Dip k ${}) :ruleset unfold)\n",
            name,
            global(&name)
        );
    }

    if sentences.is_empty() {
        out.push_str(";; (none: no identity side calls a sentence)\n\n");
    }
    Ok(())
}

fn corpus(out: &mut String, prog: &Program, posed: &[Posed]) -> Result<(), String> {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; The claims
;; ---------------------------------------------------------------------------

;; **One `push`/`pop` scope each, and that is not tidiness.** Identities are
;; independent claims, and sharing an e-graph between them makes each one's cost
;; depend on its neighbours — badly. `discarded_work_on_copies` says
;; `X = nothing`, so proving it puts a four-node program into `(Empty)`'s class;
;; `(Empty)` is the tail of every term in the file, so every suffix position in
;; every other claim starts matching a program. All five together stop finishing
;; at the fourth round. Scoped, each proves in about twenty milliseconds and the
;; total is the sum.
;;
;; What stays outside a scope is what is genuinely shared: the sorts, the
;; equations, and the library's sentence bodies. That is the theory. What goes
;; inside is one question.

"#,
    );

    for id in posed {
        let lhs = ir::build(prog.library(), id.lhs, &mut HashSet::new());
        let rhs = ir::build(prog.library(), id.rhs, &mut HashSet::new());
        let g = global(&id.name);
        let _ = writeln!(out, ";; identity {}", id.name);
        let _ = writeln!(out, "(push)");
        let _ = writeln!(out, "(let ${}__lhs {})", g, seq(prog, &lhs)?);
        let _ = writeln!(out, "(let ${}__rhs {})", g, seq(prog, &rhs)?);
        out.push_str(SCHEDULE);
        let _ = writeln!(out, "(check (= ${}__lhs ${}__rhs))", g, g);
        let _ = writeln!(out, "(pop)\n");
    }
    Ok(())
}

/// What every claim is run with.
///
/// `splice` and `analysis` saturate between every step — a concatenation has to
/// reduce before a window can match through it, and a law that reads an arity
/// cannot fire until the arity is there. Both are cheap and both terminate.
///
/// `unfold`, `framing` and `laws` are *run*, not saturated: each can fire on its
/// own output, so the `repeat` is what bounds them, and how far it gets before
/// it stops being affordable is what the file is for.
const SCHEDULE: &str = r#"(run-schedule
  (saturate (run splice))
  (saturate (run analysis))
  (repeat 4
    (run unfold)
    (run framing)
    (run laws)
    (saturate (run splice))
    (saturate (run analysis))))
"#;

/// Schedules worth trying by hand, written out once at the end.
fn notes(out: &mut String) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Other things to try
;; ---------------------------------------------------------------------------

;; Paste one of these over a claim's `run-schedule`, inside its own scope.
;;
;; The roll laws, which grow the term on purpose and which nothing places today:
;;
;;   (run-schedule (repeat 3 (run rolls) (run laws)
;;                           (saturate (run splice)) (saturate (run analysis))))
;;
;; Deeper, when a claim looks close and merely runs out of rounds. Watch the
;; clock: several laws grow the term, so this is not free.
;;
;;   (run-schedule (saturate (run splice)) (saturate (run analysis))
;;                 (repeat 8 (run unfold) (run framing) (run laws)
;;                           (saturate (run splice)) (saturate (run analysis))))
;;
;; `(print-stats)` before a `(check ...)` says which rules were doing the work.
"#,
    );
}

// ---------------------------------------------------------------------------
// Terms
// ---------------------------------------------------------------------------

/// A node sequence, as a cons list: `[a, b]` is `(Cons a (Cons b (Empty)))`.
///
/// There is exactly one spelling of a given sequence, which is the property the
/// whole encoding rests on — a window matches where it sits, with nothing
/// normalized first.
fn seq(prog: &Program, nodes: &[Node]) -> Result<String, String> {
    let mut out = "(Empty)".to_string();
    for n in nodes.iter().rev() {
        out = format!("(Cons {} {})", node(prog, n)?, out);
    }
    Ok(out)
}

fn node(prog: &Program, n: &Node) -> Result<String, String> {
    Ok(match n {
        Node::Op(inst) => format!("(Op {})", instr(prog, inst)?),
        Node::Call { depth, target } => {
            format!("(Call {} \"{}\")", depth, serial::sentence_name(prog, *target)?)
        }
        Node::Dip { depth, body, .. } => format!("(Dip {} {})", depth, seq(prog, body)?),
        Node::Branch {
            then_body,
            else_body,
            ..
        } => format!(
            "(Branch {} {})",
            seq(prog, then_body)?,
            seq(prog, else_body)?
        ),
    })
}

fn instr(prog: &Program, inst: &Instruction) -> Result<String, String> {
    Ok(match inst {
        Instruction::Push(v) => format!("(Push (Lit \"{}\"))", escape(&serial::value_text(prog, v)?)),
        Instruction::Drop => "(Drop)".to_string(),
        Instruction::Pick(d) => format!("(Pick {})", d),
        Instruction::Roll(d) => format!("(Roll {})", d),
        Instruction::Tuple(n) => format!("(Tuple {})", n),
        Instruction::Untuple(n) => format!("(Untuple {})", n),
        Instruction::Panic | Instruction::Assert | Instruction::AssertEqual => {
            return Err(format!(
                "`{}` cannot fail under the precondition every equation is stated \
                 under, so it has no spelling here",
                inst
            ));
        }
        Instruction::Dip(..) | Instruction::Branch(..) => {
            return Err(format!(
                "`{}` is a node rather than an operation, and should not have \
                 reached the instruction writer",
                inst
            ));
        }
        other => format!("(Prim \"{}\")", other),
    })
}

/// The instructions that are named rather than shaped: everything with no
/// operand a law reads.
fn primitives() -> Vec<Instruction> {
    vec![
        Instruction::Equal,
        Instruction::Greater,
        Instruction::Less,
        Instruction::Add,
        Instruction::Subtract,
        Instruction::Multiply,
        Instruction::Divide,
        Instruction::Modulo,
        Instruction::Not,
        Instruction::Negate,
        Instruction::And,
        Instruction::Or,
        Instruction::ConstStringLen,
        Instruction::ConstStringCharAt,
        Instruction::IsInt,
        Instruction::IsBool,
        Instruction::IsFloat,
        Instruction::IsConstString,
        Instruction::IsSymbol,
        Instruction::IsTuple,
        Instruction::TupleLength,
    ]
}

/// Every sentence the identities can reach, transitively.
///
/// Bounding the `unfold` rules by reachability is what keeps the file finite in
/// practice: the precondition already refuses `#[recursive]`, so expansion
/// terminates, but a corpus holds thousands of sentences and an identity names
/// at most a handful.
fn reachable(prog: &Program, posed: &[Posed]) -> BTreeSet<SentenceIndex> {
    let mut seen = BTreeSet::new();
    let mut queue: Vec<SentenceIndex> = Vec::new();

    for id in posed {
        for side in [id.lhs, id.rhs] {
            collect_calls(
                &ir::build(prog.library(), side, &mut HashSet::new()),
                &mut queue,
            );
        }
    }

    while let Some(target) = queue.pop() {
        if !seen.insert(target) {
            continue;
        }
        let body = ir::build(prog.library(), target, &mut HashSet::new());
        collect_calls(&body, &mut queue);
    }
    seen
}

fn collect_calls(nodes: &[Node], out: &mut Vec<SentenceIndex>) {
    for n in nodes {
        match n {
            Node::Call { target, .. } => out.push(*target),
            Node::Dip { body, .. } => collect_calls(body, out),
            Node::Branch {
                then_body,
                else_body,
                ..
            } => {
                collect_calls(then_body, out);
                collect_calls(else_body, out);
            }
            Node::Op(_) => {}
        }
    }
}

/// A name egglog will take after a `$`, which its globals require.
fn global(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}

/// A string that survives being written between double quotes.
fn escape(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_repeated_instruction_conses_onto_the_tail() {
        assert_eq!(drops(0, "rest"), "rest");
        assert_eq!(drops(1, "rest"), "(Cons (Op (Drop)) rest)");
        assert_eq!(
            drops(2, "rest"),
            "(Cons (Op (Drop)) (Cons (Op (Drop)) rest))"
        );
    }

    #[test]
    fn a_roll_run_repeats_the_same_depth() {
        assert_eq!(
            rolls(2, 2, "rest"),
            "(Cons (Op (Roll 2)) (Cons (Op (Roll 2)) rest))"
        );
    }

    #[test]
    fn a_global_name_keeps_only_what_egglog_will_take() {
        assert_eq!(global("identities::testing_a_test"), "identities__testing_a_test");
    }

    #[test]
    fn a_quote_in_a_const_string_is_escaped() {
        assert_eq!(escape(r#"say "hi""#), r#"say \"hi\""#);
    }
}
