//! The corpus, posed to an e-graph.
//!
//! `prove` searches with a tactic. This writes the same question down in
//! [egglog]'s language instead — the equations as rewrite rules, the identities
//! as two terms and a `check` — so that saturation can be asked whether the two
//! sides meet. Nothing here reads an answer back; what comes out is a file to
//! run, and `docs/egglog.md` is the design it is a first cut of.
//!
//! **This is a producer of a question, not of a proof.** Whatever an e-graph
//! concludes has to come back as a `.hand` derivation and be replayed before it
//! means anything, so nothing in this module is on the path that decides an
//! identity. That is why it may be approximate where [`crate::rule`] may not.
//!
//! [egglog]: https://github.com/egraphs-good/egglog
//!
//! ## What is approximate, and why that is allowed
//!
//! - **A value is opaque.** `Val` holds the literal's `.hand` spelling and
//!   nothing else, so two values are equal exactly when they are written the
//!   same. That is right for every literal the format can spell, and it costs
//!   `eval`, which would have to compute on one. `eval` is not emitted.
//! - **Provenance is dropped**, as it is on the wire and in
//!   [`crate::ir::same_effect`]. An e-graph's whole business is merging terms
//!   that are equal, and origins would keep two identical blocks apart.
//! - **Several equations are emitted in one direction only**, because the other
//!   reading has a variable the pattern does not bind — `counit` backward has to
//!   invent a `d` — or because it can fire on its own output forever. Each one
//!   says which, beside it in the generated file.
//! - **The laws with a repetition count** — `drop^m`, `(roll d)^(d+1)` — have no
//!   single pattern, so they are emitted instantiated at every width up to a
//!   bound.

use std::collections::{BTreeSet, HashSet};
use std::fmt::Write as _;

use bytecode::arity::op_arity;
use bytecode::{Instruction, SentenceIndex};

use crate::ir::{self, Node};
use crate::program::Program;
use crate::serial;

/// One identity, as the emitter needs it: a name and its two sides.
pub(crate) struct Posed {
    pub(crate) name: String,
    pub(crate) lhs: SentenceIndex,
    pub(crate) rhs: SentenceIndex,
}

/// How wide the instantiated laws are spelled out.
///
/// `annihilate` and `roll_cycle` are stated with a repetition count, which a
/// pattern cannot hold, so each is emitted once per width. Three is enough for
/// every arity in the corpus and keeps the rule count in two figures.
pub(crate) const DEFAULT_BOUND: i64 = 3;

/// The whole file: sorts, facts, equations, the corpus, and the checks.
pub(crate) fn emit(prog: &Program, posed: &[Posed], bound: i64) -> Result<String, String> {
    let mut out = String::new();

    header(&mut out, posed, bound);
    sorts(&mut out);
    facts(&mut out)?;
    arity_rules(&mut out);
    assoc(&mut out);
    laws(&mut out, bound);
    roll_laws(&mut out, bound);

    let sentences = reachable(prog, posed);
    unfolding(&mut out, prog, &sentences)?;
    corpus(&mut out, prog, posed)?;
    schedule(&mut out, posed);

    Ok(out)
}

// ---------------------------------------------------------------------------
// The file, section by section
// ---------------------------------------------------------------------------

fn header(out: &mut String, posed: &[Posed], bound: i64) {
    let _ = write!(
        out,
        r#";; Generated by `prove --emit-egglog`. Do not edit; regenerate.
;;
;; {} identit{}, posed to an e-graph. Run it with:
;;
;;     egglog this-file.egg
;;
;; `check` aborts the run at the first claim that does not close, so the checks
;; are listed one per line at the bottom and the fastest way to look at one
;; identity is to emit it alone:
;;
;;     prove <dir> --emit-egglog one.egg --filter <name>
;;
;; Instantiated laws are spelled out to width {}; `--egglog-bound` moves that.
;;
;; The equations are `docs/tactics.md`; the design this is a first cut of is
;; `docs/egglog.md`. What is NOT emitted, and why:
;;
;;   eval          needs to compute on a literal, and a literal is opaque here
;;   unframe       stated with a repetition count on both sides at once
;;   copy_nat      the same, and it is the law worth reaching for next
;;   annihilate    emitted, but only for m = 1 and m = 2 (the flagged and
;;                 unflagged readings); m = 0 would fire on every `Cat`
;;
;; and the readings that are emitted forward only, each marked below:
;; `counit`, `counit_under`, `collapse`, `fuse`, `fold_branch`, `commute`,
;; `split_bool`, `retest`, `cancel_tuple`, `annihilate`.
;;
;; `elim_dip0` is the exception: its backward reading invents a frame, which
;; under saturation never stops, so it is emitted into its own ruleset and
;; *run* once a round rather than saturated.

"#,
        posed.len(),
        if posed.len() == 1 { "y" } else { "ies" },
        bound,
    );
}

fn sorts(out: &mut String) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Sorts
;; ---------------------------------------------------------------------------

;; A literal by its `.hand` spelling, which is injective for every value the
;; format can write: `9`, `true`, `"text"`, `1.5`, `(1, 2)`, `mod::sym`.
(datatype Val (Lit String))

;; The instructions an equation looks *inside* get a shape; the rest are named.
;; `panic`, `assert` and `assert_eq` have no spelling here for the same reason
;; they have none on the wire: every equation is stated about code that cannot
;; fail.
(datatype Instr
  (Push Val)
  (Drop)
  (Pick i64)
  (Roll i64)
  (Tuple i64)
  (Untuple i64)
  (Prim String))

;; A term is a sequence of nodes, and a sequence is a monoid — not a cons list.
;; Seven of the twenty-two laws bind a whole subsequence, and `elim_dip0` alone
;; settles it: splicing a frame's body into the enclosing sequence *is*
;; concatenation. `One` rather than `Unit`, which egglog has taken.
;;
;; A `Call` names its sentence, never an index: an index is an offset into one
;; assembly of one corpus.
(datatype*
  (Node
    (Op Instr)
    (Call i64 String)
    (Dip i64 Seq)
    (Branch Seq Seq))
  (Seq
    (Empty)
    (One Node)
    (Cat Seq Seq)))

"#,
    );
}

fn facts(out: &mut String) -> Result<(), String> {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Facts the search cannot re-derive
;; ---------------------------------------------------------------------------

;; The applier re-derives every fact a step rests on, against the real library.
;; A searcher in another process has no library, so the facts are dumped here —
;; and a wrong table costs a rejected derivation, never a wrong proof, because
;; `Rule::check` asks again when the step is applied.
;;
;; `commutative` and `yields-bool` are swept against the interpreter over every
;; operand shape, so what is copied here is a measured fact rather than a
;; comment.

;; Its own ruleset, saturated before every round of laws: an arity is a fact
;; about a term, so it has to be settled before a law that reads one can fire.
(ruleset analysis)

(relation commutative (Instr))
(relation yields-bool (Instr))

;; `untuple n` leaves a flag like the others, but it carries an operand, so it
;; is shaped rather than named and cannot be a row.
(rule ((= i (Untuple k))) ((yields-bool i)) :ruleset analysis)

"#,
    );

    for inst in primitives() {
        let name = format!("{}", inst);
        if inst.commutative() {
            let _ = writeln!(out, "(commutative (Prim \"{}\"))", name);
        }
    }
    out.push('\n');
    for inst in primitives() {
        let name = format!("{}", inst);
        if inst.yields_bool() {
            let _ = writeln!(out, "(yields-bool (Prim \"{}\"))", name);
        }
    }

    out.push_str(
        r#"
;; Arity, as a lattice rather than a number.
;;
;; It is NOT an e-class invariant: `pick 1 ; drop` is (2 -> 2) where nothing is
;; (0 -> 0), which is why an identity is held to its net change rather than to
;; its full arity. What is invariant is the net; the input requirement is an
;; upper bound that falls when two terms are found equal. So `min` on the one
;; and `:no-merge` on the other, which is exactly what the two mean.
;;
;; A rule firing on a joined-down bound is still sound: everything in a class is
;; equal, so a law true of the member with the lower requirement is true of the
;; class. What is *not* sound is writing that number into a derivation — the
;; step's arguments have to be recomputed from the concrete term. See
;; `docs/egglog.md`.

(function ar-in  (Node) i64 :merge (min old new))
(function ar-net (Node) i64 :no-merge)
(function sq-in  (Seq) i64 :merge (min old new))
(function sq-net (Seq) i64 :no-merge)

;; The primitive instructions, from `bytecode::arity::op_arity`.
(relation prim-arity (String i64 i64))
"#,
    );

    for inst in primitives() {
        let name = format!("{}", inst);
        let (n, m) = op_arity(&inst)
            .ok_or_else(|| format!("`{}` has no arity, which should not happen", name))?;
        let _ = writeln!(out, "(prim-arity \"{}\" {} {})", name, n, m - n);
    }

    out.push('\n');
    Ok(())
}

fn arity_rules(out: &mut String) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Arity, computed bottom-up
;; ---------------------------------------------------------------------------

;; `pick d` is (d+1 -> d+2), `roll d` is (d+1 -> d+1), `tuple n` is (n -> 1),
;; `untuple n` is (1 -> n+1) — the parametric ones are rules rather than rows.
(rule ((= n (Op (Push c))))    ((set (ar-in n) 0)     (set (ar-net n) 1)) :ruleset analysis)
(rule ((= n (Op (Drop))))      ((set (ar-in n) 1)     (set (ar-net n) -1)) :ruleset analysis)
(rule ((= n (Op (Pick d))))    ((set (ar-in n) (+ d 1)) (set (ar-net n) 1)) :ruleset analysis)
(rule ((= n (Op (Roll d))))    ((set (ar-in n) (+ d 1)) (set (ar-net n) 0)) :ruleset analysis)
(rule ((= n (Op (Tuple k))))   ((set (ar-in n) k)     (set (ar-net n) (- 1 k))) :ruleset analysis)
(rule ((= n (Op (Untuple k)))) ((set (ar-in n) 1)     (set (ar-net n) k)) :ruleset analysis)
(rule ((= n (Op (Prim p))) (prim-arity p i v)) ((set (ar-in n) i) (set (ar-net n) v)) :ruleset analysis)

;; A frame adds its depth to what the body needs and changes nothing else.
(rule ((= n (Dip k b)) (= i (sq-in b)) (= v (sq-net b)))
      ((set (ar-in n) (+ k i)) (set (ar-net n) v)) :ruleset analysis)

;; A branch pops the condition, then runs an arm. Both arms leave the same net
;; or the sentence would not have compiled, so either one answers.
(rule ((= n (Branch t e)) (= it (sq-in t)) (= ie (sq-in e)) (= vt (sq-net t)))
      ((set (ar-in n) (+ 1 (max it ie))) (set (ar-net n) (- vt 1))) :ruleset analysis)

(rule ((= s (Empty))) ((set (sq-in s) 0) (set (sq-net s) 0)) :ruleset analysis)
(rule ((= s (One n)) (= i (ar-in n)) (= v (ar-net n)))
      ((set (sq-in s) i) (set (sq-net s) v)) :ruleset analysis)

;; Composition: the second half's requirement is met by whatever the first half
;; left, so what the whole needs is the larger of the two, measured in the same
;; place.
(rule ((= s (Cat a b)) (= ia (sq-in a)) (= va (sq-net a)) (= ib (sq-in b)))
      ((set (sq-in s) (max ia (- ib va)))) :ruleset analysis)
(rule ((= s (Cat a b)) (= va (sq-net a)) (= vb (sq-net b)))
      ((set (sq-net s) (+ va vb))) :ruleset analysis)

"#,
    );
}

fn assoc(out: &mut String) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; The monoid
;; ---------------------------------------------------------------------------

;; Bookkeeping, not a law: two `Seq` terms that differ only by association are
;; the same `Vec<Node>`, so a translator reading a proof out of here drops these
;; steps rather than spelling them.
;;
;; **Off by default, and that is a measurement rather than a guess.** Turning it
;; on is what makes `discarded_work_on_copies` run past ninety seconds without
;; closing; with it off the same claim proves in well under a second. The reason
;; is that a term is emitted right-associated and every law below is written
;; against that spine, so a window whose sequence variable is a single node or a
;; suffix is already matchable — which is most of them. Re-association earns its
;; cost only for a variable spanning several nodes away from a spine boundary,
;; and nothing in the corpus needs one yet.
;;
;; So: add `(saturate (run assoc))` to the schedule when a claim will not close
;; and you think a mid-sequence window is why. Expect it to be expensive.
;;
;; The *unit* laws are a separate ruleset and are always on. They are cheap —
;; they only ever shrink a term — and they are not optional: a law that leaves
;; nothing behind leaves `(Empty)` sitting in a spine, and a right-hand side one
;; node long has to meet it. `testing_a_test_by_name` is the case that says so.
;;
;; Both are one-directional on purpose. Read the other way they build
;; `(Cat (Empty) (Cat (Empty) ...))` forever.
(ruleset units)
(rewrite (Cat (Empty) a) a :ruleset units)
(rewrite (Cat a (Empty)) a :ruleset units)

(ruleset assoc)
(birewrite (Cat (Cat a b) c) (Cat a (Cat b c)) :ruleset assoc)

"#,
    );
}

/// The equations of `docs/tactics.md`, in whichever readings a pattern can hold.
fn laws(out: &mut String, bound: i64) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; The equations
;; ---------------------------------------------------------------------------

(ruleset laws)

;; collapse: dip k { dip j { A } } = dip (k+j) { A }
;; Forward only: k+j does not say which k and which j.
(rule ((= n (Dip k (One (Dip j a)))))
      ((union n (Dip (+ k j) a)))
      :ruleset laws)

;; elim_dip0: dip 0 { A } = A
;; Forward only: read backward it wraps any run in a frame, and then wraps that.
(rewrite (Cat (One (Dip 0 a)) rest) (Cat a rest) :ruleset laws)

;; interchange: X ; D_k = D_(k-m+n) ; X, for X : n -> m, k >= m
;; X is one node here, which is where most of its work is; a whole-sequence X
;; wants the same rule with `x` a `Seq`, and costs an associativity match.
(rule ((= s (Cat (One x) (Cat (One (Dip k b)) rest)))
       (= i (ar-in x)) (= v (ar-net x)) (>= k (+ i v)))
      ((union s (Cat (One (Dip (- k v) b)) (Cat (One x) rest))))
      :ruleset laws)
(rule ((= s (Cat (One (Dip k b)) (Cat (One x) rest)))
       (= i (ar-in x)) (= v (ar-net x)) (>= k i))
      ((union s (Cat (One x) (Cat (One (Dip (+ k v) b)) rest))))
      :ruleset laws)

;; fuse: dip k { A } ; dip k { B } = dip k { A B }
;; Forward only: read backward the split point is free.
(rewrite (Cat (One (Dip k a)) (Cat (One (Dip k b)) rest))
         (Cat (One (Dip k (Cat a b))) rest)
         :ruleset laws)

;; hoist: dip (k+1) { X } ; branch { A } { B }
;;      = branch { dip k { X } ; A } { dip k { X } ; B }
;; Both readings: forward pushes a computation into both arms, backward is the
;; last step of factoring a shared prefix out.
(rule ((= s (Cat (One (Dip k x)) (Cat (One (Branch a b)) rest))) (> k 0))
      ((union s (Cat (One (Branch (Cat (One (Dip (- k 1) x)) a)
                                  (Cat (One (Dip (- k 1) x)) b))) rest)))
      :ruleset laws)
(rule ((= s (Cat (One (Branch (Cat (One (Dip k x)) a)
                              (Cat (One (Dip k x)) b))) rest)))
      ((union s (Cat (One (Dip (+ k 1) x)) (Cat (One (Branch a b)) rest))))
      :ruleset laws)

;; distribute: branch { A } { B } ; C = branch { A C } { B C }
;; Both readings; backward factors a shared suffix, which no matcher can do.
(birewrite (Cat (One (Branch a b)) c) (One (Branch (Cat a c) (Cat b c)))
           :ruleset laws)

;; fold_branch: push c ; branch { A } { B } = the arm c selects
;; Selected by truthiness, and `false` is the only falsy value — so `push 1`
;; takes the *then* arm, as firmly as `push false` takes the else arm.
;; Forward only: an arm does not say what condition chose it.
(rule ((= s (Cat (One (Op (Push c))) (Cat (One (Branch a b)) rest)))
       (!= c (Lit "false")))
      ((union s (Cat a rest)))
      :ruleset laws)
(rule ((= s (Cat (One (Op (Push (Lit "false")))) (Cat (One (Branch a b)) rest))))
      ((union s (Cat b rest)))
      :ruleset laws)

;; commute: roll 1 ; op = op, for a commutative op
;; Forward only: read backward it prepends a `roll 1` forever.
(rule ((= s (Cat (One (Op (Roll 1))) (Cat (One (Op o)) rest))) (commutative o))
      ((union s (Cat (One (Op o)) rest)))
      :ruleset laws)

;; split_bool: pick 0 ; is_bool ; branch { branch { push true } { push false } } { }
;;           = nothing
;; Forward only: backward is a case split, which needs somewhere to stand.
(rewrite (Cat (One (Op (Pick 0)))
              (Cat (One (Op (Prim "is_bool")))
                   (Cat (One (Branch (One (Branch (One (Op (Push (Lit "true"))))
                                                  (One (Op (Push (Lit "false"))))))
                                     (Empty)))
                        rest)))
         rest
         :ruleset laws)

;; counit: pick d ; drop = nothing            (copy, discard the copy)
;; counit_under: pick 0 ; dip 1 { drop } = nothing   (discard the original)
;; Forward only: backward has to invent a `d`, and then another.
(rewrite (Cat (One (Op (Pick d))) (Cat (One (Op (Drop))) rest)) rest :ruleset laws)
(rewrite (Cat (One (Op (Pick 0))) (Cat (One (Dip 1 (One (Op (Drop))))) rest)) rest
         :ruleset laws)

;; retest: pick 0 ; branch { branch { A } { B } ; R } { Q }
;;       = pick 0 ; branch { drop ; A ; R } { Q },  and the mirror
;; The same value tested twice answers the same, so the other inner arm is dead.
;; Forward only: the dead arm is not recoverable from the collapsed one.
(rule ((= s (Cat (One (Op (Pick 0)))
                 (Cat (One (Branch (Cat (One (Branch a b)) r) q)) rest))))
      ((union s (Cat (One (Op (Pick 0)))
                     (Cat (One (Branch (Cat (One (Op (Drop))) (Cat a r)) q)) rest))))
      :ruleset laws)
(rule ((= s (Cat (One (Op (Pick 0)))
                 (Cat (One (Branch q (Cat (One (Branch a b)) r))) rest))))
      ((union s (Cat (One (Op (Pick 0)))
                     (Cat (One (Branch q (Cat (One (Op (Drop))) (Cat b r)))) rest))))
      :ruleset laws)

;; copy_const: push c ; pick 0 = push c ; push c
(birewrite (Cat (One (Op (Push c))) (Cat (One (Op (Pick 0))) rest))
           (Cat (One (Op (Push c))) (Cat (One (Op (Push c))) rest))
           :ruleset laws)

;; copy_assoc: pick d ; pick 0 = pick d ; dip 1 { pick d }
;; Neither side is smaller; the point is that one copy ends up in a frame.
(birewrite (Cat (One (Op (Pick d))) (Cat (One (Op (Pick 0))) rest))
           (Cat (One (Op (Pick d))) (Cat (One (Dip 1 (One (Op (Pick d))))) rest))
           :ruleset laws)

;; bool_result: op ; is_bool = op ; drop ; push true, for an op yielding a bool
;; The only fact here about an instruction's codomain, and the only one no
;; rewriting could reach.
(rule ((= s (Cat (One (Op o)) (Cat (One (Op (Prim "is_bool"))) rest)))
       (yields-bool o))
      ((union s (Cat (One (Op o))
                     (Cat (One (Op (Drop)))
                          (Cat (One (Op (Push (Lit "true")))) rest)))))
      :ruleset laws)
(rule ((= s (Cat (One (Op o))
                 (Cat (One (Op (Drop)))
                      (Cat (One (Op (Push (Lit "true")))) rest))))
       (yields-bool o))
      ((union s (Cat (One (Op o)) (Cat (One (Op (Prim "is_bool"))) rest))))
      :ruleset laws)

;; cancel_tuple: tuple n ; untuple n = push true
;; Forward only: `push true` does not say which n. The converse order is not a
;; no-op and has no equation.
(rewrite (Cat (One (Op (Tuple n))) (Cat (One (Op (Untuple n))) rest))
         (Cat (One (Op (Push (Lit "true")))) rest)
         :ruleset laws)

"#,
    );

    annihilate(out, bound);
}

/// `X ; drop^m` = `drop^n`, one rule per `(n, m)` up to the bound.
///
/// The count is on both sides and a pattern cannot hold one, so the law is
/// spelled out. `m = 0` is left out: its pattern is a bare `Cat`, which is every
/// sequence in the file.
fn annihilate(out: &mut String, bound: i64) {
    out.push_str(
        r#";; annihilate: X ; drop^m = drop^n, for X : n -> m
;; The workhorse, and the one law stated with a repetition count — so it is
;; spelled out once per width. Forward only: read backward it introduces an X
;; the pattern cannot name, which is `introduce`, and which is exactly the step
;; a search here cannot take. Widths below are m in 1..=2, n in 0..=bound.
"#,
    );
    for m in 1..=2i64 {
        for n in 0..=bound {
            let _ = writeln!(
                out,
                "(rule ((= s (Cat x {}))\n       (= (sq-in x) {}) (= (sq-net x) {}))\n      \
                 ((union s {}))\n      :ruleset laws)",
                drops(m, "rest"),
                n,
                m - n,
                drops(n, "rest"),
            );
        }
    }
    out.push('\n');
}

/// `drop` repeated `k` times in front of `tail`, as a `Seq` expression.
fn drops(k: i64, tail: &str) -> String {
    let mut s = tail.to_string();
    for _ in 0..k {
        s = format!("(Cat (One (Op (Drop))) {})", s);
    }
    s
}

/// `roll d` repeated `k` times in front of `tail`.
fn rolls(d: i64, k: i64, tail: &str) -> String {
    let mut s = tail.to_string();
    for _ in 0..k {
        s = format!("(Cat (One (Op (Roll {}))) {})", d, s);
    }
    s
}

fn roll_laws(out: &mut String, bound: i64) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; The one generative reading that is emitted
;; ---------------------------------------------------------------------------

;; elim_dip0 backward: put a frame that hides nothing around the head of a
;; sequence. Read forward it splices; read backward, here, it *introduces*, and
;; introducing is how factoring starts — a shared prefix has to be in a frame
;; before `hoist` can lift it out of two arms.
;;
;; Every other backward reading that invents material is left out, because under
;; saturation it never stops. This one is emitted anyway because it does not have
;; to be saturated: the schedule says `(run framing)`, one application per round,
;; so the nesting goes exactly as deep as there are rounds. That is the
;; difference between a reading that cannot be searched and one that has to be
;; *scheduled* — `a_value_tested_twice` is the corpus claim that turns on it, and
;; it does not close without this.
(ruleset framing)
(rule ((= s (Cat x rest))) ((union s (Cat (One (Dip 0 x)) rest))) :ruleset framing)

;; ---------------------------------------------------------------------------
;; The roll laws, which nothing places yet
;; ---------------------------------------------------------------------------

;; `roll_cycle`, `pick_roll` and `unframe` are equations a script may name, but
;; no matcher looks for any of them — what each reading should search for is an
;; open question. A pattern is not a matcher, so two of the three arrive here
;; for free.
;;
;; Their own ruleset because `pick_roll` forward fires on every `pick` and grows
;; the term every time. Add `(run rolls)` to the schedule to turn them on.
(ruleset rolls)

;; pick_roll: pick d = dip d { pick 0 } ; roll d
(birewrite (Cat (One (Op (Pick d))) rest)
           (Cat (One (Dip d (One (Op (Pick 0))))) (Cat (One (Op (Roll d))) rest))
           :ruleset rolls)

;; roll_cycle: (roll d)^(d+1) = nothing. A rotation of d+1 things has order d+1.
;; Forward only, and instantiated: the count is the law.
"#,
    );
    for d in 0..=bound {
        let _ = writeln!(
            out,
            "(rewrite {} rest :ruleset rolls)",
            rolls(d, d + 1, "rest")
        );
    }
    out.push_str(
        "\n;; unframe is not emitted: dip d { X } ; (roll (d+m-1))^m = (roll (d+n-1))^n ; X\n\
         ;; has a repetition count on *both* sides at once, driven by an arity the\n\
         ;; pattern would also have to read. It wants the same treatment as\n\
         ;; annihilate, one rule per (d, n, m), which is a cube rather than a square.\n\n",
    );
}

fn unfolding(
    out: &mut String,
    prog: &Program,
    sentences: &BTreeSet<SentenceIndex>,
) -> Result<(), String> {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; What the library says
;; ---------------------------------------------------------------------------

;; That `Call { k, S }` may be replaced by S's body is not a law of the calculus
;; — it is the axiom the library contributes by defining S, and it says nothing
;; about any other sentence. So it is one birewrite per sentence rather than a
;; rule, and only for the sentences the identities can reach.
;;
;; Read backward it folds, which `docs/identities.md` calls the real gap because
;; nothing can read a window and say which sentence to fold into. Congruence
;; does not have that problem: the body is in a class and so is the call.
(ruleset unfold)

"#,
    );

    for &target in sentences {
        let name = serial::sentence_name(prog, target)?;
        let body = ir::build(prog.library(), target, &mut HashSet::new());
        let _ = writeln!(
            out,
            "(let ${} {})",
            global(&name),
            seq(prog, &body)?
        );
        let _ = writeln!(
            out,
            "(birewrite (One (Call 0 \"{}\")) ${} :ruleset unfold)",
            name,
            global(&name)
        );
        let _ = writeln!(
            out,
            "(birewrite (Dip k ${}) (Call k \"{}\") :ruleset unfold)\n",
            global(&name),
            name
        );
    }

    if sentences.is_empty() {
        out.push_str(";; (none: no identity side calls a sentence)\n\n");
    }
    Ok(())
}

fn corpus(out: &mut String, prog: &Program, posed: &[Posed]) -> Result<(), String> {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; The claims
;; ---------------------------------------------------------------------------

"#,
    );
    for id in posed {
        let lhs = ir::build(prog.library(), id.lhs, &mut HashSet::new());
        let rhs = ir::build(prog.library(), id.rhs, &mut HashSet::new());
        let _ = writeln!(out, ";; identity {}", id.name);
        let _ = writeln!(
            out,
            "(let ${}__lhs {})",
            global(&id.name),
            seq(prog, &lhs)?
        );
        let _ = writeln!(
            out,
            "(let ${}__rhs {})\n",
            global(&id.name),
            seq(prog, &rhs)?
        );
    }
    Ok(())
}

fn schedule(out: &mut String, posed: &[Posed]) {
    out.push_str(
        r#";; ---------------------------------------------------------------------------
;; Running it
;; ---------------------------------------------------------------------------

;; Analysis saturates before every round, because a law that reads an arity
;; cannot fire until the arity is there. `repeat` rather than `saturate` on the
;; laws: several of them grow the term, so this does not converge, and how far
;; it gets before it stops being affordable is what the file is for.
(run-schedule
  (repeat 4
    (saturate (run units))
    (saturate (run analysis))
    (run unfold)
    (run framing)
    (run laws)))

;; Associativity, when a mid-sequence window is what a claim is missing. This is
;; the expensive one — see the note above the ruleset.
;; (run-schedule (repeat 2 (saturate (run units)) (saturate (run analysis)) (saturate (run assoc)) (run laws)))

;; The roll laws, which grow the term on purpose.
;; (run-schedule (repeat 3 (saturate (run units)) (saturate (run analysis)) (run rolls) (run laws)))

(print-stats)

"#,
    );

    out.push_str(";; One per line, because `check` stops the run at the first failure.\n");
    for id in posed {
        let _ = writeln!(
            out,
            "(check (= ${}__lhs ${}__rhs))   ;; {}",
            global(&id.name),
            global(&id.name),
            id.name
        );
    }
}

// ---------------------------------------------------------------------------
// Terms
// ---------------------------------------------------------------------------

/// A node sequence, right-associated and always closed with `(Empty)`.
///
/// The `(Empty)` is not decoration. Every law below is written as a window with
/// a `rest` behind it, so a window that runs to the end of a sequence has to
/// have something there to bind — drop the terminator and `push 9 ; pick 0`
/// stops matching `copy_const`, whose pattern needs a `Cat` where the bare form
/// leaves a `One`.
fn seq(prog: &Program, nodes: &[Node]) -> Result<String, String> {
    let mut out = "(Empty)".to_string();
    for n in nodes.iter().rev() {
        out = format!("(Cat (One {}) {})", node(prog, n)?, out);
    }
    Ok(out)
}

fn node(prog: &Program, n: &Node) -> Result<String, String> {
    Ok(match n {
        Node::Op(inst) => format!("(Op {})", instr(prog, inst)?),
        Node::Call { depth, target } => {
            format!("(Call {} \"{}\")", depth, serial::sentence_name(prog, *target)?)
        }
        Node::Dip { depth, body, .. } => format!("(Dip {} {})", depth, seq(prog, body)?),
        Node::Branch {
            then_body,
            else_body,
            ..
        } => format!(
            "(Branch {} {})",
            seq(prog, then_body)?,
            seq(prog, else_body)?
        ),
    })
}

fn instr(prog: &Program, inst: &Instruction) -> Result<String, String> {
    Ok(match inst {
        Instruction::Push(v) => format!("(Push (Lit \"{}\"))", escape(&serial::value_text(prog, v)?)),
        Instruction::Drop => "(Drop)".to_string(),
        Instruction::Pick(d) => format!("(Pick {})", d),
        Instruction::Roll(d) => format!("(Roll {})", d),
        Instruction::Tuple(n) => format!("(Tuple {})", n),
        Instruction::Untuple(n) => format!("(Untuple {})", n),
        Instruction::Panic | Instruction::Assert | Instruction::AssertEqual => {
            return Err(format!(
                "`{}` cannot fail under the precondition every equation is stated \
                 under, so it has no spelling here",
                inst
            ));
        }
        Instruction::Dip(..) | Instruction::Branch(..) => {
            return Err(format!(
                "`{}` is a node rather than an operation, and should not have \
                 reached the instruction writer",
                inst
            ));
        }
        other => format!("(Prim \"{}\")", other),
    })
}

/// The instructions that are named rather than shaped: everything with no
/// operand a law reads.
fn primitives() -> Vec<Instruction> {
    vec![
        Instruction::Equal,
        Instruction::Greater,
        Instruction::Less,
        Instruction::Add,
        Instruction::Subtract,
        Instruction::Multiply,
        Instruction::Divide,
        Instruction::Modulo,
        Instruction::Not,
        Instruction::Negate,
        Instruction::And,
        Instruction::Or,
        Instruction::ConstStringLen,
        Instruction::ConstStringCharAt,
        Instruction::IsInt,
        Instruction::IsBool,
        Instruction::IsFloat,
        Instruction::IsConstString,
        Instruction::IsSymbol,
        Instruction::IsTuple,
        Instruction::TupleLength,
    ]
}

/// Every sentence the identities can reach, transitively.
///
/// Bounding the `unfold` rules by reachability is what keeps the file finite in
/// practice: the precondition already refuses `#[recursive]`, so expansion
/// terminates, but a corpus holds thousands of sentences and an identity names
/// at most a handful.
fn reachable(prog: &Program, posed: &[Posed]) -> BTreeSet<SentenceIndex> {
    let mut seen = BTreeSet::new();
    let mut queue: Vec<SentenceIndex> = Vec::new();

    for id in posed {
        for side in [id.lhs, id.rhs] {
            collect_calls(
                &ir::build(prog.library(), side, &mut HashSet::new()),
                &mut queue,
            );
        }
    }

    while let Some(target) = queue.pop() {
        if !seen.insert(target) {
            continue;
        }
        let body = ir::build(prog.library(), target, &mut HashSet::new());
        collect_calls(&body, &mut queue);
    }
    seen
}

fn collect_calls(nodes: &[Node], out: &mut Vec<SentenceIndex>) {
    for n in nodes {
        match n {
            Node::Call { target, .. } => out.push(*target),
            Node::Dip { body, .. } => collect_calls(body, out),
            Node::Branch {
                then_body,
                else_body,
                ..
            } => {
                collect_calls(then_body, out);
                collect_calls(else_body, out);
            }
            Node::Op(_) => {}
        }
    }
}

/// A name egglog will take after a `$`, which its globals require.
fn global(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}

/// A string that survives being written between double quotes.
fn escape(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_sequence_is_right_associated_and_ends_in_empty() {
        assert_eq!(drops(0, "rest"), "rest");
        assert_eq!(drops(1, "rest"), "(Cat (One (Op (Drop))) rest)");
        assert_eq!(
            drops(2, "rest"),
            "(Cat (One (Op (Drop))) (Cat (One (Op (Drop))) rest))"
        );
    }

    #[test]
    fn a_roll_run_repeats_the_same_depth() {
        assert_eq!(
            rolls(2, 2, "rest"),
            "(Cat (One (Op (Roll 2))) (Cat (One (Op (Roll 2))) rest))"
        );
    }

    #[test]
    fn a_global_name_keeps_only_what_egglog_will_take() {
        assert_eq!(global("identities::testing_a_test"), "identities__testing_a_test");
    }

    #[test]
    fn a_quote_in_a_const_string_is_escaped() {
        assert_eq!(escape(r#"say "hi""#), r#"say \"hi\""#);
    }
}
