//! Checking that every identity a corpus states has a proof that discharges it.
//!
//! `.hana` states the claim, the sibling `.hant` proves it, and this walks the
//! two together. What it is for is that a claim should be worth something:
//! `rewrite` can show two programs are interchangeable, but the showing was
//! printed and lost, so nothing re-checked it when the library changed
//! underneath.
//!
//! **A proof is one-sided, and the comparison is up to inlining.** The tactic
//! rewrites the left-hand side; the result must be the right-hand side, either
//! as written or after both are unfolded. Every step is an equation, so what
//! the run leaves behind is a derivation LHS ⇒ RHS — one linear script, which
//! is a thing that can be replayed, printed, stepped through and diffed.
//!
//! Unfolding being an equation like any other is what makes the second reading
//! sound: it is the axiom the library contributes by defining a sentence, so
//! two terms with the same fully inlined form are equal. The fold-back is
//! generated by running the *forward* unfold on the right-hand side and
//! inverting the script — which is why `inv(unfold)` having no matcher costs
//! nothing. Nothing can read a window and say which sentence to fold into, and
//! nothing has to: the step already names it.
//!
//! So the derivation **ends at the right-hand side**, and the replay says so.
//! That is what the comparison alone could not: a script that stopped at what
//! the tactic reached left the last hop an equality test rather than a splice
//! the applier had to accept.
//!
//! Two things here deliberately differ from `rewrite`, and both are the same
//! difference: `rewrite` explores, and this decides.
//!
//! - **A miss fails a proof**, where in `rewrite` it is a diagnostic that still
//!   prints the tree. `at(9, sink)` in a proof is a claim that there is
//!   something at 9; when there is not, the proof is written against a tree it
//!   no longer describes, even if the goal was reached anyway.
//! - **`--check` is on by default.** In `rewrite` it is opt-in because the
//!   listing is the answer and the check only costs time. Here the answer is
//!   *yes* or *no*, and a wrong yes is worse than a slow run.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use bytecode::{Identity, IdentityIndex, Library, SentenceIndex, SourceMap};

use crate::applier::apply_script;
use crate::diff::side_by_side;
use crate::engine::{Env, Tactic, TacticError, miss_report, run as run_tactic};
use crate::ir::{Node, build, same_effect_seq};
use crate::print::render_nodes;
use crate::program::Program;
use crate::rule::{Script, invert};
use crate::script::{Definitions, PRELUDE, ProofFile, ScriptError};
use crate::{DEFAULT_FUEL, Precondition, check_preconditions, precondition_explanation};

pub(crate) struct Options {
    pub(crate) dir: PathBuf,
    pub(crate) filter: Option<String>,
    pub(crate) fuel: u64,
    pub(crate) check: bool,
    pub(crate) show_script: bool,
    pub(crate) stack: bool,
    pub(crate) tactic_files: Vec<PathBuf>,
}

impl Default for Options {
    fn default() -> Self {
        Options {
            dir: PathBuf::new(),
            filter: None,
            fuel: DEFAULT_FUEL,
            // On by default, where `rewrite` has it opt-in. This is the tool
            // whose job is to be sure.
            check: true,
            show_script: false,
            stack: false,
            tactic_files: Vec::new(),
        }
    }
}

/// `prove` distinguishes "a claim is wrong" from "the tree will not build",
/// because in CI those want different reactions.
pub(crate) const OK: i32 = 0;
pub(crate) const FAILED: i32 = 1;
pub(crate) const BROKEN: i32 = 2;

/// Checks every identity in the corpus, writing its report to `out`.
///
/// Writing to a `Write` rather than to stdout is what makes this testable
/// without a subprocess — every failure mode below has a test that reads the
/// report back.
pub(crate) fn run(opts: &Options, out: &mut dyn std::io::Write) -> std::io::Result<i32> {
    let (sources, library) = match crate::load(&opts.dir) {
        Ok(pair) => pair,
        Err(err) => {
            write!(out, "{}", err)?;
            if !err.ends_with('\n') {
                writeln!(out)?;
            }
            return Ok(BROKEN);
        }
    };

    let mut base = Definitions::new();
    base.load(PRELUDE)
        .expect("the built-in prelude parses; if it does not, that is a bug");
    for path in &opts.tactic_files {
        let source = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(err) => {
                writeln!(out, "error: reading '{}': {}", path.display(), err)?;
                return Ok(BROKEN);
            }
        };
        if let Err(err) = base.load(&source) {
            write!(
                out,
                "{}",
                err.render_in(&source, &path.display().to_string())
            )?;
            return Ok(BROKEN);
        }
    }

    let prog = Program::new(&library);
    // The comparison is up to inlining, and this is what does it. Compiled once
    // from the prelude, where it is `repeat(bu(each(unfold)))`.
    let inline = match base.compile_with("unfold_all", Some(&prog)) {
        Ok(t) => t,
        Err(err) => {
            write!(out, "{}", err.render("unfold_all"))?;
            writeln!(out, "(this is a bug in the built-in prelude)")?;
            return Ok(BROKEN);
        }
    };

    let files = match collect(&opts.dir, &sources, &library, &prog, &base) {
        Ok(files) => files,
        Err(problems) => {
            // All of them, not the first. A tree missing three `.hant` files
            // should say so once rather than over three runs.
            for problem in &problems {
                writeln!(out, "{}", problem)?;
            }
            return Ok(FAILED);
        }
    };

    check_all(&library, &prog, &files, &inline, opts, out)
}

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

/// One `.hant`, parsed, with each of its proofs paired to what it proves.
struct ProvenFile {
    hant: PathBuf,
    source: String,
    file: ProofFile,
    /// `(identity, index into file.proofs)`, in the order the identities were
    /// stated.
    pairs: Vec<(IdentityIndex, usize)>,
}

/// Pairs every stated identity with its proof, or says everything that is wrong.
///
/// The rule is one `.hant` beside each `.hana`, checked as a bijection in both
/// directions. It governs where a proof *lives*, not what it may reference — so
/// the day a proof may cite an identity stated elsewhere, nothing here changes.
fn collect(
    dir: &Path,
    sources: &SourceMap,
    library: &Library,
    prog: &Program,
    base: &Definitions,
) -> Result<Vec<ProvenFile>, Vec<String>> {
    let mut out = Vec::new();
    let mut problems = Vec::new();
    let mut expected: HashSet<PathBuf> = HashSet::new();

    // The files that state something, in the order the assembler read them, so
    // the report is deterministic.
    let mut files = Vec::new();
    for identity in &library.identities {
        if !files.contains(&identity.span.file) {
            files.push(identity.span.file);
        }
    }

    for file in files {
        let stated = library.identities_in(file);
        let Some(hana) = sources.path(file) else {
            problems.push(format!(
                "error: '{}' states an identity but is not a file on disk\n  \
                 An identity is proved in the file beside the one that states it, \
                 and there is no beside here.",
                sources.name(file)
            ));
            continue;
        };
        let hant = hana.with_extension("hant");
        expected.insert(hant.clone());

        let Ok(source) = std::fs::read_to_string(&hant) else {
            problems.push(missing_hant(library, &stated, hana, &hant));
            continue;
        };

        let parsed = match ProofFile::parse(&source, base, prog) {
            Ok(f) => f,
            Err(err) => {
                problems.push(err.render_in(&source, &hant.display().to_string()));
                continue;
            }
        };

        // Every proof names an identity stated in this file...
        let mut proved: Vec<Option<usize>> = vec![None; stated.len()];
        for (i, proof) in parsed.proofs.iter().enumerate() {
            match resolve_here(library, &stated, &proof.path) {
                Ok(pos) => proved[pos] = Some(i),
                Err(why) => problems.push(
                    ScriptError::about(
                        format!("no identity `{}` to prove here", proof.path),
                        proof.path_span,
                        why,
                    )
                    .render_in(&source, &hant.display().to_string()),
                ),
            }
        }
        // ...and every identity stated here has one.
        let mut pairs = Vec::new();
        for (pos, slot) in proved.iter().enumerate() {
            match slot {
                Some(i) => pairs.push((stated[pos], *i)),
                None => problems.push(format!(
                    "error: '{}' has no proof of `{}`\n  \
                     It is stated in '{}'; write `proof {} = <tactic>;`",
                    hant.display(),
                    library.identities[stated[pos]].name,
                    hana.display(),
                    short(&library.identities[stated[pos]].name)
                )),
            }
        }

        out.push(ProvenFile {
            hant,
            source,
            file: parsed,
            pairs,
        });
    }

    // A `.hant` beside a `.hana` that states nothing, or beside no `.hana` at
    // all, is invisible to the walk above — which is exactly the case worth
    // catching, since renaming a `.hana` orphans its proofs silently.
    for stray in hant_files(dir) {
        if !expected.contains(&stray) {
            problems.push(format!(
                "error: '{}' proves nothing\n  \
                 No identity is stated in '{}'. A `.hant` is read as the sibling of a \
                 `.hana` that states one; pass it to `--tactics` if it holds tactic \
                 definitions only.",
                stray.display(),
                stray.with_extension("hana").display()
            ));
        }
    }

    if problems.is_empty() {
        Ok(out)
    } else {
        Err(problems)
    }
}

fn missing_hant(library: &Library, stated: &[IdentityIndex], hana: &Path, hant: &Path) -> String {
    let wanted: Vec<String> = stated
        .iter()
        .map(|i| {
            format!(
                "    proof {} = <tactic>;",
                short(&library.identities[*i].name)
            )
        })
        .collect();
    format!(
        "error: '{}' has no proofs\n  \
         '{}' states {}, and an identity is proved in the `.hant` beside the `.hana` \
         that states it.\n  Write:\n\n{}",
        hant.display(),
        hana.display(),
        plural(stated.len(), "identity", "identities"),
        wanted.join("\n")
    )
}

/// Every `.hant` under `dir`, recursively — `tests/advent/` holds `.hana` files
/// too, so a flat listing would miss a `.hant` beside one.
fn hant_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(at) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&at) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "hant") {
                out.push(path);
            }
        }
    }
    out.sort();
    out
}

/// Which of this file's identities a proof names.
///
/// Resolution is suffix matching over the identities *stated in this file*,
/// rather than module-relative resolution: a `.hant` is not part of the module
/// tree — its sibling's own module path is decided by whoever wrote
/// `mod identities;` — so it has no scope of its own, and this is the reading a
/// sentence and a symbol already get.
fn resolve_here(library: &Library, stated: &[IdentityIndex], path: &str) -> Result<usize, String> {
    let suffix = format!("::{}", path);
    let matches: Vec<usize> = stated
        .iter()
        .enumerate()
        .filter(|(_, i)| {
            let name = &library.identities[**i].name;
            name == path || name.ends_with(&suffix)
        })
        .map(|(pos, _)| pos)
        .collect();
    match matches[..] {
        [only] => Ok(only),
        _ if matches.len() > 1 => Err("it is ambiguous here; write more of the path".to_string()),
        // It may exist somewhere else, and saying where is the whole content of
        // the mistake.
        _ => Err(match library.identity_by_name(path) {
            Ok(other) => format!(
                "`{}` is stated in another file, and an identity is proved beside \
                 where it is stated",
                library.identities[other].name
            ),
            Err(_) => {
                let names: Vec<&str> = stated
                    .iter()
                    .map(|i| library.identities[*i].name.as_str())
                    .collect();
                format!("this file states: {}", names.join(", "))
            }
        }),
    }
}

// ---------------------------------------------------------------------------
// Checking
// ---------------------------------------------------------------------------

fn check_all(
    library: &Library,
    prog: &Program,
    files: &[ProvenFile],
    inline: &Tactic,
    opts: &Options,
    out: &mut dyn std::io::Write,
) -> std::io::Result<i32> {
    let mut selected = Vec::new();
    let mut filtered = 0usize;
    for file in files {
        for (identity, proof) in &file.pairs {
            let wanted = match &opts.filter {
                Some(sub) => library.identities[*identity].name.contains(sub),
                None => true,
            };
            if wanted {
                selected.push((file, *identity, *proof));
            } else {
                filtered += 1;
            }
        }
    }

    writeln!(
        out,
        "Proving {}...",
        plural(selected.len(), "identity", "identities")
    )?;

    let mut passed = 0usize;
    let mut failed = 0usize;
    for (file, index, proof) in &selected {
        let identity = &library.identities[*index];
        write!(out, "identity {} ... ", identity.name)?;
        match check(prog, identity, file, *proof, inline, opts) {
            Ok(proven) => {
                passed += 1;
                writeln!(out, "ok ({})", proven.closed.summary())?;
                if opts.show_script {
                    writeln!(out)?;
                    for line in derivation(prog, &proven) {
                        writeln!(out, "{}", line)?;
                    }
                    writeln!(out)?;
                }
            }
            Err(failure) => {
                failed += 1;
                writeln!(out, "FAILED")?;
                writeln!(out)?;
                for line in failure.render(prog, identity, file, *proof, opts) {
                    writeln!(out, "{}", line)?;
                }
                writeln!(out)?;
            }
        }
    }

    writeln!(out)?;
    writeln!(
        out,
        "identity result: {}. {} passed; {} failed; {} filtered out",
        if failed == 0 { "ok" } else { "FAILED" },
        passed,
        failed,
        filtered
    )?;
    Ok(if failed == 0 { OK } else { FAILED })
}

/// Why an identity did not come out proved.
enum Failure {
    /// A side the equations cannot speak about at all.
    Side(Precondition, &'static str, String),
    /// The proof expression does not resolve.
    Proof(String),
    /// The tactic ran out of fuel, was refused, or failed.
    ///
    /// Boxed, as is its sibling below: a `TacticError` carries the last two
    /// dozen steps of a run that would not settle, which is exactly what a
    /// reader wants and is far too much to widen every `Result` in this file by.
    Ran(Box<TacticError>),
    /// Inlining one side to compare them ran out of fuel. Named separately from
    /// `Ran`, since it is not the proof's own failure and reads as one.
    Inlining(&'static str, Box<TacticError>),
    /// An aimed step matched nothing.
    Missed(Vec<String>),
    /// It ran, and landed somewhere else.
    NotReached(Vec<Node>),
    /// The script does not reproduce the run. A bug here, not in the proof.
    Replay(String),
}

/// A discharged claim: the derivation, and how it closed.
struct Proven {
    /// The whole thing, `LHS ⇒ RHS`.
    script: Script,
    /// How it got there, which is what a listing has to say.
    closed: Closed,
}

/// The two ways a proof reaches the right-hand side.
enum Closed {
    /// The tactic landed on it as written. The derivation is the proof's own
    /// steps and nothing else.
    Exactly { steps: usize },
    /// It landed somewhere the right-hand side *inlines to*. Unfolding is an
    /// equation like any other — the axiom the library contributes by defining
    /// a sentence — so two terms with the same fully inlined form are equal.
    UpToInlining {
        /// The proof's own steps.
        steps: usize,
        /// Inlining what the proof reached.
        unfolded: usize,
        /// Folding the right-hand side back up, which is the *forward* unfold
        /// of the right-hand side read backwards.
        folded: usize,
    },
}

impl Closed {
    /// The count a passing line reports.
    fn summary(&self) -> String {
        match self {
            Closed::Exactly { steps } => plural(*steps, "step", "steps"),
            Closed::UpToInlining {
                steps,
                unfolded,
                folded,
            } => format!(
                "{} + {} up to inlining",
                plural(*steps, "step", "steps"),
                unfolded + folded
            ),
        }
    }
}

/// Runs one proof, returning its derivation.
fn check(
    prog: &Program,
    identity: &Identity,
    file: &ProvenFile,
    proof: usize,
    inline: &Tactic,
    opts: &Options,
) -> Result<Proven, Failure> {
    // Both sides, not only the one that gets rewritten: the right-hand side is
    // the term the claim is measured against, so it has to be one the equations
    // can speak about too. It is also what makes the inlining below terminate,
    // since `#[recursive]` is refused and that property is closed over
    // reachability.
    for (side, which) in [(identity.lhs, "left-hand"), (identity.rhs, "right-hand")] {
        if let Err(p) = check_preconditions(prog, side) {
            return Err(Failure::Side(p, which, prog.library().names[side].clone()));
        }
    }

    let tactic = compile(prog, file, proof)?;
    let lhs = tree(prog, identity.lhs);
    let rhs = tree(prog, identity.rhs);

    let env = Env::new(prog, opts.fuel, opts.check);
    let (got, s1) =
        run_tactic(&env, &tactic, lhs.clone()).map_err(|e| Failure::Ran(Box::new(e)))?;

    let misses = env.misses();
    if !misses.is_empty() {
        return Err(Failure::Missed(miss_report(&misses)));
    }

    // The claim that makes a script a derivation rather than a log: replaying
    // it against a fresh build reproduces the run *exactly*. Checked here on
    // the proof's own steps, where `==` is available and is the stronger
    // comparison — the end of the whole derivation is measured by effect.
    let mut replayed = lhs.clone();
    match apply_script(prog, &mut replayed, &s1, opts.check) {
        Ok(()) if replayed == got => {}
        Ok(()) => return Err(Failure::Replay("it produced a different tree".to_string())),
        Err(err) => return Err(Failure::Replay(err.to_string())),
    }

    let steps = s1.len();
    // Compared by effect, not by `==`. Phase 4 mints a fresh `SentenceIndex`
    // for every inline block, so the right-hand side's blocks can never share
    // provenance with anything the left-hand side rewrote into — and provenance
    // is not part of a term's identity.
    let (script, closed) = if same_effect_seq(&got, &rhs) {
        (s1, Closed::Exactly { steps })
    } else {
        // Up to inlining. The fold-back is generated by running the *forward*
        // unfold on the right-hand side and inverting the script — which is why
        // `inv(unfold)` having no matcher costs nothing here. Nothing can read a
        // window and say which sentence to fold into, and nothing has to: the
        // step already names it.
        let (left, s2) = normalize(prog, inline, got.clone(), "left-hand", opts)?;
        let (right, s3) = normalize(prog, inline, rhs.clone(), "right-hand", opts)?;
        if !same_effect_seq(&left, &right) {
            return Err(Failure::NotReached(got));
        }
        let (unfolded, folded) = (s2.len(), s3.len());
        let mut script = s1;
        script.extend(s2);
        script.extend(invert(&s3));
        (
            script,
            Closed::UpToInlining {
                steps,
                unfolded,
                folded,
            },
        )
    };

    // And the derivation ends at the right-hand side. That is the thing the old
    // one-sided check could not say: its script stopped at what the tactic
    // reached, and the last hop was an equality test rather than a splice the
    // applier had to accept.
    let mut landed = lhs;
    match apply_script(prog, &mut landed, &script, opts.check) {
        Ok(()) if same_effect_seq(&landed, &rhs) => Ok(Proven { script, closed }),
        Ok(()) => Err(Failure::Replay(
            "it did not land on the right-hand side".to_string(),
        )),
        Err(err) => Err(Failure::Replay(err.to_string())),
    }
}

/// Inlines every call, and says which side it was doing it to.
///
/// A separate `Env` per side, so the two scripts stay separable — the left's is
/// appended and the right's is inverted. Neither can record a miss: `unfold_all`
/// aims at nothing.
fn normalize(
    prog: &Program,
    inline: &Tactic,
    nodes: Vec<Node>,
    which: &'static str,
    opts: &Options,
) -> Result<(Vec<Node>, Script), Failure> {
    let env = Env::new(prog, opts.fuel, opts.check);
    run_tactic(&env, inline, nodes).map_err(|e| Failure::Inlining(which, Box::new(e)))
}

fn compile(prog: &Program, file: &ProvenFile, proof: usize) -> Result<Tactic, Failure> {
    file.file
        .compile(&file.file.proofs[proof], prog)
        .map_err(|e| Failure::Proof(e.render_in(&file.source, &file.hant.display().to_string())))
}

fn tree(prog: &Program, root: SentenceIndex) -> Vec<Node> {
    build(prog.library(), root, &mut HashSet::new())
}

impl Failure {
    fn render(
        &self,
        prog: &Program,
        identity: &Identity,
        file: &ProvenFile,
        proof: usize,
        opts: &Options,
    ) -> Vec<String> {
        let mut out = Vec::new();
        match self {
            Failure::Side(p, which, name) => {
                let lines = precondition_explanation(*p, name);
                out.push(format!("  the {} side cannot be rewritten.", which));
                out.push(String::new());
                out.push(format!("  {}", lines[0]));
                out.extend(lines[1..].iter().cloned());
            }
            Failure::Proof(rendered) => {
                out.push("  the proof does not compile.".to_string());
                out.push(String::new());
                out.extend(rendered.lines().map(|l| l.to_string()));
            }
            Failure::Ran(err) => {
                out.push(format!("  the proof did not run: {}", err));
                out.extend(cited(file, proof));
            }
            Failure::Inlining(which, err) => {
                out.push(format!(
                    "  the proof ran, but inlining the {} side to compare them",
                    which
                ));
                out.push(format!("  did not finish: {}", err));
                out.push(String::new());
                out.push(
                    "  The two sides are compared up to inlining, so both are unfolded".to_string(),
                );
                out.push(
                    "  when the proof does not land on the right-hand side as written.".to_string(),
                );
                out.extend(cited(file, proof));
            }
            Failure::Missed(report) => {
                out.push("  an aimed step in the proof matched nothing.".to_string());
                out.push(String::new());
                out.extend(report.iter().map(|l| indented(l)));
                out.push(String::new());
                out.push(
                    "  Here that fails the proof rather than warning: a proof aimed at a"
                        .to_string(),
                );
                out.push(
                    "  tree it no longer describes is wrong even where the goal was reached."
                        .to_string(),
                );
                out.extend(cited(file, proof));
            }
            Failure::NotReached(got) => {
                out.push("  the proof ran, but did not reach the right-hand side,".to_string());
                out.push("  and inlining both sides did not reconcile them either.".to_string());
                out.extend(cited(file, proof));
                out.push(String::new());
                let want = tree(prog, identity.rhs);
                // Without origins: the two sides came from two sentences, so
                // every `<inline>` label differs and none of the differences
                // mean anything. `same_effect_seq` ignores them for the same
                // reason, and a listing being compared has to agree with the
                // comparison.
                let left = render_nodes(prog, got, opts.stack, true, false);
                let right = render_nodes(prog, &want, opts.stack, true, false);
                let rows = side_by_side(&left, &right, "what it reached", "the right-hand side");
                if rows.is_empty() {
                    // Two listings that read alike but are not the same by
                    // effect. That is a bug in one of them rather than in the
                    // proof, so show both rather than nothing at all.
                    out.push(
                        "  The two listings read alike but are not the same term.".to_string(),
                    );
                    out.extend(left);
                    out.push(String::new());
                    out.extend(right);
                } else {
                    out.extend(rows);
                }
                // The listing above is what is *written*, which is the useful
                // orientation. When the difference is inside a call, the way to
                // see it is to open the two sides up — and each is addressable
                // by name, which is what that naming is for.
                out.push(String::new());
                out.push(format!(
                    "  To see inside the calls: rewrite <dir> '{}::lhs' -t unfold_all",
                    short_path(&identity.name)
                ));
                out.push("  and the same for `::rhs`.".to_string());
            }
            Failure::Replay(why) => {
                out.push("  the proof reached the right-hand side, but its derivation".to_string());
                out.push(format!("  does not replay: {}", why));
                out.push(String::new());
                out.push("  That is a bug in the rewriter, not in the proof.".to_string());
            }
        }
        out
    }
}

/// The derivation, in the segments it was built from.
///
/// A proof that closed exactly has one. A proof that closed up to inlining has
/// three, and saying which is which matters: a reader looking at a hundred
/// unfolds followed by a hundred folds is owed an explanation of why the term
/// went somewhere and came back.
fn derivation(prog: &Program, proven: &Proven) -> Vec<String> {
    match proven.closed {
        Closed::Exactly { .. } => crate::derivation_lines(prog, "derivation", &proven.script),
        Closed::UpToInlining {
            steps,
            unfolded,
            folded,
        } => {
            let (a, rest) = proven.script.split_at(steps);
            let (b, c) = rest.split_at(unfolded);
            debug_assert_eq!(c.len(), folded);
            let mut out = crate::derivation_lines(prog, "the proof", a);
            out.push(String::new());
            out.extend(crate::derivation_lines(prog, "inlining what it reached", b));
            out.push(String::new());
            out.extend(crate::derivation_lines(
                prog,
                "folding the right-hand side back up",
                c,
            ));
            out
        }
    }
}

/// The proof as written, and where. What a reader needs to go and fix it.
fn cited(file: &ProvenFile, proof: usize) -> Vec<String> {
    let def = &file.file.proofs[proof];
    let (start, end) = def.span;
    let text = file.source[start..end.min(file.source.len())].trim();
    let line = file.source[..start].matches('\n').count() + 1;
    vec![
        String::new(),
        format!("  proof: {}", text),
        format!("   --> {}:{}", file.hant.display(), line),
    ]
}

/// Two spaces in front of a line, except an empty one — which would otherwise
/// become trailing whitespace in the report.
fn indented(line: &str) -> String {
    if line.is_empty() {
        String::new()
    } else {
        format!("  {}", line)
    }
}

/// Enough of a name to be unambiguous on the command line, which is the
/// trailing segment — the reading `resolve_sentence` gives.
fn short_path(name: &str) -> &str {
    name.rsplit("::").next().unwrap_or(name)
}

fn short(name: &str) -> &str {
    name.rsplit("::").next().unwrap_or(name)
}

fn plural(n: usize, one: &str, many: &str) -> String {
    if n == 1 {
        format!("{} {}", n, one)
    } else {
        format!("{} {}", n, many)
    }
}

// ---------------------------------------------------------------------------
// The command line
// ---------------------------------------------------------------------------

/// Parses arguments and runs. The binary is one line over this.
pub(crate) fn cli() -> i32 {
    let mut opts = Options::default();
    let mut positional: Vec<String> = Vec::new();

    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut i = 0;
    while i < args.len() {
        let arg = args[i].as_str();
        let mut value = |name: &str| -> Option<String> {
            i += 1;
            match args.get(i) {
                Some(v) => Some(v.clone()),
                None => {
                    eprintln!("{} needs a value", name);
                    None
                }
            }
        };
        match arg {
            "--filter" => match value("--filter") {
                Some(v) => opts.filter = Some(v),
                None => return BROKEN,
            },
            "--tactics" => match value("--tactics") {
                Some(v) => opts.tactic_files.push(PathBuf::from(v)),
                None => return BROKEN,
            },
            "--fuel" => match value("--fuel").map(|raw| raw.parse()) {
                Some(Ok(v)) => opts.fuel = v,
                Some(Err(_)) => {
                    eprintln!("--fuel needs a number");
                    return BROKEN;
                }
                None => return BROKEN,
            },
            "--no-check" => opts.check = false,
            "--show-script" => opts.show_script = true,
            "--stack" => opts.stack = true,
            "-h" | "--help" => {
                usage();
                return OK;
            }
            flag if flag.starts_with('-') => {
                eprintln!("Unknown flag: {}", flag);
                usage();
                return BROKEN;
            }
            other => positional.push(other.to_string()),
        }
        i += 1;
    }

    if positional.len() != 1 {
        usage();
        return BROKEN;
    }
    opts.dir = PathBuf::from(&positional[0]);

    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    match run(&opts, &mut handle) {
        Ok(code) => code,
        Err(err) => {
            eprintln!("error writing the report: {}", err);
            BROKEN
        }
    }
}

fn usage() {
    eprintln!("Usage: prove <directory> [options]");
    eprintln!();
    eprintln!("  Checks that every `identity` stated in the corpus rooted at");
    eprintln!("  <directory>/main.hana has a proof in the `.hant` beside the");
    eprintln!("  `.hana` that states it, and that the proof discharges it.");
    eprintln!();
    eprintln!("  --filter <substr>    only identities whose name contains this.");
    eprintln!("  --tactics <file>     tactic definitions loaded before every .hant.");
    eprintln!("  --show-script        print each derivation, one step per line.");
    eprintln!("  --stack              show what each slot holds, in a failure diff.");
    eprintln!("  --fuel <n>           rule firings before giving up.");
    eprintln!("  --no-check           skip the net-stack-effect check on every step.");
    eprintln!("                       It is on by default here and opt-in in `rewrite`:");
    eprintln!("                       this is the tool whose job is to be sure.");
    eprintln!();
    eprintln!("Exit: 0 every identity proved, 1 one did not, 2 the corpus would not build.");
    eprintln!();
    eprintln!("A proof is found with `rewrite`, which addresses an identity's sides");
    eprintln!("by name:");
    eprintln!();
    eprintln!("  rewrite tests 'my_identity::lhs' -t 'cleanup' --show-script");
    eprintln!("  rewrite tests 'my_identity::rhs'");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A corpus in a temp directory, since discovery is about files on disk.
    struct Corpus(PathBuf);

    impl Corpus {
        fn new(name: &str, hana: &str, hant: Option<&str>) -> Corpus {
            let dir = std::env::temp_dir().join(format!("hanoi_prove_{}", name));
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(&dir).unwrap();
            std::fs::write(dir.join("main.hana"), hana).unwrap();
            if let Some(hant) = hant {
                std::fs::write(dir.join("main.hant"), hant).unwrap();
            }
            Corpus(dir)
        }

        fn write(&self, name: &str, text: &str) -> &Corpus {
            std::fs::write(self.0.join(name), text).unwrap();
            self
        }

        fn run(&self) -> (i32, String) {
            self.run_with(Options {
                dir: self.0.clone(),
                ..Options::default()
            })
        }

        fn run_with(&self, mut opts: Options) -> (i32, String) {
            opts.dir = self.0.clone();
            let mut out = Vec::new();
            let code = run(&opts, &mut out).expect("writing to a Vec cannot fail");
            (code, String::from_utf8(out).expect("the report is utf-8"))
        }
    }

    impl Drop for Corpus {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    /// `is_bool ; is_bool` is `bool_result` and then an annihilation, which is
    /// what `cleanup` does in two steps.
    const TESTING_A_TEST: &str =
        "identity testing_a_test { is_bool is_bool } = { drop 0 push true };";

    #[test]
    fn a_correct_proof_passes() {
        let c = Corpus::new(
            "pass",
            TESTING_A_TEST,
            Some("proof testing_a_test = cleanup;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, OK, "{}", report);
        assert!(
            report.contains("identity testing_a_test ... ok"),
            "{}",
            report
        );
        assert!(report.contains("1 passed; 0 failed"), "{}", report);
    }

    /// The failure that matters: the tactic ran, and landed somewhere else.
    /// What the report owes is the difference, not the fact of it.
    #[test]
    fn a_proof_that_lands_elsewhere_shows_the_difference() {
        let c = Corpus::new(
            "elsewhere",
            "identity foo { is_bool is_bool } = { drop 0 push false };",
            Some("proof foo = cleanup;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(
            report.contains("did not reach the right-hand side"),
            "{}",
            report
        );
        assert!(report.contains("what it reached"), "{}", report);
        assert!(report.contains("push true"), "{}", report);
        assert!(report.contains("push false"), "{}", report);
        // The proof is quoted back with where to go and fix it.
        assert!(report.contains("proof: cleanup"), "{}", report);
    }

    /// Provenance is not part of a term's identity, so a diff must not report
    /// two `<inline>` labels — which never match across two sentences — as the
    /// difference.
    #[test]
    fn a_failure_diff_does_not_report_provenance() {
        let c = Corpus::new(
            "provenance",
            "identity foo { pick 0 branch { push 1 } { push 2 } } \
             = { pick 0 branch { push 1 } { push 9 } };",
            Some("proof foo = id;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(!report.contains("<inline>"), "{}", report);
        assert!(report.contains("push 2"), "{}", report);
        assert!(report.contains("push 9"), "{}", report);
    }

    #[test]
    fn an_identity_with_no_proof_is_reported() {
        let c = Corpus::new(
            "unproved",
            "identity a { drop 0 } = { drop 0 };\nidentity b { drop 0 } = { drop 0 };",
            Some("proof a = id;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(report.contains("has no proof of `b`"), "{}", report);
        assert!(report.contains("proof b = <tactic>;"), "{}", report);
    }

    #[test]
    fn a_missing_hant_says_what_to_write() {
        let c = Corpus::new("no_hant", TESTING_A_TEST, None);
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(report.contains("has no proofs"), "{}", report);
        assert!(
            report.contains("proof testing_a_test = <tactic>;"),
            "{}",
            report
        );
    }

    #[test]
    fn a_proof_of_an_identity_stated_elsewhere_says_where() {
        let c = Corpus::new(
            "elsewhere_file",
            "mod other;\nidentity here { drop 0 } = { drop 0 };",
            Some("proof here = id;\nproof there = id;"),
        );
        c.write("other.hana", "identity there { drop 0 } = { drop 0 };");
        c.write("other.hant", "proof there = id;");
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(
            report.contains("no identity `there` to prove here"),
            "{}",
            report
        );
        assert!(report.contains("stated in another file"), "{}", report);
    }

    #[test]
    fn an_unknown_identity_lists_what_the_file_does_state() {
        let c = Corpus::new(
            "unknown",
            TESTING_A_TEST,
            Some("proof testing_a_test = cleanup;\nproof nosuch = id;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(report.contains("no identity `nosuch`"), "{}", report);
        assert!(
            report.contains("this file states: testing_a_test"),
            "{}",
            report
        );
    }

    /// Renaming a `.hana` orphans its proofs, and nothing else would notice.
    #[test]
    fn a_hant_beside_no_identity_is_reported() {
        let c = Corpus::new(
            "stray",
            TESTING_A_TEST,
            Some("proof testing_a_test = cleanup;"),
        );
        c.write("orphan.hant", "proof gone = id;");
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(report.contains("orphan.hant' proves nothing"), "{}", report);
    }

    /// The divergence from `rewrite`, which treats a miss as a diagnostic and
    /// prints the tree anyway.
    #[test]
    fn an_aimed_step_that_misses_fails_the_proof() {
        let c = Corpus::new(
            "miss",
            TESTING_A_TEST,
            Some("proof testing_a_test = at(9, sink); cleanup;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(report.contains("matched nothing"), "{}", report);
        assert!(
            report.contains("fails the proof rather than warning"),
            "{}",
            report
        );
    }

    /// ...and `try` is how a proof says a miss is acceptable.
    #[test]
    fn try_says_a_miss_is_acceptable() {
        let c = Corpus::new(
            "try",
            TESTING_A_TEST,
            Some("proof testing_a_test = try(at(9, sink)); cleanup;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, OK, "{}", report);
    }

    #[test]
    fn a_side_that_can_fail_is_refused_in_rewrites_own_words() {
        let c = Corpus::new(
            "fallible",
            "identity bad { assert } = { assert };",
            Some("proof bad = id;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(
            report.contains("the left-hand side cannot be rewritten"),
            "{}",
            report
        );
        assert!(report.contains("can fail"), "{}", report);
        assert!(report.contains("docs/totality.md"), "{}", report);
    }

    #[test]
    fn a_proof_that_does_not_compile_points_at_the_word() {
        let c = Corpus::new(
            "badproof",
            TESTING_A_TEST,
            Some("proof testing_a_test = nonesuch;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(report.contains("does not compile"), "{}", report);
        assert!(report.contains("main.hant:1:24"), "{}", report);
    }

    #[test]
    fn the_filter_selects_by_name() {
        let c = Corpus::new(
            "filter",
            "identity keep_me { drop 0 } = { drop 0 };\nidentity skip_me { drop 0 } = { drop 0 };",
            Some("proof keep_me = id;\nproof skip_me = id;"),
        );
        let (code, report) = c.run_with(Options {
            filter: Some("keep".to_string()),
            ..Options::default()
        });
        assert_eq!(code, OK, "{}", report);
        assert!(
            report.contains("1 passed; 0 failed; 1 filtered out"),
            "{}",
            report
        );
    }

    /// A tree missing three things should say so once, not over three runs.
    #[test]
    fn every_problem_is_reported_not_just_the_first() {
        let c = Corpus::new(
            "all_problems",
            "identity a { drop 0 } = { drop 0 };\nidentity b { drop 0 } = { drop 0 };",
            Some("proof nosuch = id;"),
        );
        let (_, report) = c.run();
        assert!(report.contains("no identity `nosuch`"), "{}", report);
        assert!(report.contains("has no proof of `a`"), "{}", report);
        assert!(report.contains("has no proof of `b`"), "{}", report);
    }

    /// A `.hana` that states nothing needs no `.hant`, which is nearly every
    /// file in the corpus.
    #[test]
    fn a_hana_that_states_nothing_needs_no_hant() {
        let c = Corpus::new("quiet", "sentence a { }", None);
        let (code, report) = c.run();
        assert_eq!(code, OK, "{}", report);
        assert!(report.contains("Proving 0 identities"), "{}", report);
    }

    #[test]
    fn a_corpus_that_will_not_build_is_a_different_exit_code() {
        let c = Corpus::new("broken", "sentence a { frobnicate }", None);
        let (code, _) = c.run();
        assert_eq!(code, BROKEN);
    }

    #[test]
    fn a_tactics_file_is_loaded_before_every_hant() {
        let c = Corpus::new(
            "prelude",
            TESTING_A_TEST,
            Some("proof testing_a_test = mine;"),
        );
        c.write("shared.tactics", "tactic mine = cleanup;");
        let (code, report) = c.run_with(Options {
            tactic_files: vec![c.0.join("shared.tactics")],
            ..Options::default()
        });
        assert_eq!(code, OK, "{}", report);
    }

    // -----------------------------------------------------------------------
    // Up to inlining
    // -----------------------------------------------------------------------

    /// The case the whole meet-in-the-middle change is for: the right-hand side
    /// names a sentence the proof does not leave standing, so nothing the
    /// tactic does could ever land on it as written.
    const BY_NAME: &str = "#[total] function f { drop 0 push true }\n\
                           identity foo { is_bool is_bool } = { jump f };";

    #[test]
    fn a_right_hand_side_written_as_a_call_is_reconciled() {
        let c = Corpus::new("by_name", BY_NAME, Some("proof foo = cleanup;"));
        let (code, report) = c.run();
        assert_eq!(code, OK, "{}", report);
        assert!(report.contains("up to inlining"), "{}", report);
    }

    /// And the fold-back is one step, not a re-derivation: the right-hand
    /// side's own unfold script, read backwards.
    #[test]
    fn the_fold_back_is_the_unfold_script_inverted() {
        let c = Corpus::new("foldback", BY_NAME, Some("proof foo = cleanup;"));
        let (code, report) = c.run_with(Options {
            show_script: true,
            ..Options::default()
        });
        assert_eq!(code, OK, "{}", report);
        assert!(
            report.contains("folding the right-hand side back up — 1 step(s)"),
            "{}",
            report
        );
        // `<-` is the reverse reading. Forward it opens a call; backward it
        // contracts a body into one, which no matcher can look for and none
        // has to.
        assert!(report.contains("unfold <-"), "{}", report);
    }

    /// A proof that lands exactly must not pay for the machinery: no inlining
    /// segment, and the count is the proof's own steps. Without this a
    /// regression to always-normalizing would pass every other test here.
    #[test]
    fn landing_exactly_still_takes_the_short_route() {
        let c = Corpus::new(
            "short",
            TESTING_A_TEST,
            Some("proof testing_a_test = cleanup;"),
        );
        let (code, report) = c.run_with(Options {
            show_script: true,
            ..Options::default()
        });
        assert_eq!(code, OK, "{}", report);
        assert!(report.contains("ok (2 steps)"), "{}", report);
        assert!(!report.contains("up to inlining"), "{}", report);
        assert!(report.contains("derivation — 2 step(s)"), "{}", report);
    }

    /// Inlining is not a way to pass. Two sides that differ inside the call
    /// still fail, and the diff still shows what is *written*, since that is
    /// the readable orientation.
    #[test]
    fn inlining_that_does_not_reconcile_still_fails() {
        let c = Corpus::new(
            "no_reconcile",
            "#[total] function f { drop 0 push false }\n\
             identity foo { is_bool is_bool } = { jump f };",
            Some("proof foo = cleanup;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, FAILED, "{}", report);
        assert!(
            report.contains("inlining both sides did not reconcile them"),
            "{}",
            report
        );
        assert!(report.contains("jump"), "{}", report);
        // ...and it says how to see inside the call, since that is where the
        // difference is.
        assert!(report.contains("foo::lhs"), "{}", report);
    }

    /// Both directions at once: the left inlines *and* the right folds back.
    #[test]
    fn both_sides_may_need_inlining() {
        let c = Corpus::new(
            "both",
            "#[total] function l { is_bool is_bool }\n\
             #[total] function r { drop 0 push true }\n\
             identity foo { jump l } = { jump r };",
            Some("proof foo = unfold_all; cleanup;"),
        );
        let (code, report) = c.run();
        assert_eq!(code, OK, "{}", report);
        assert!(report.contains("up to inlining"), "{}", report);
    }

    #[test]
    fn show_script_prints_the_derivation() {
        let c = Corpus::new(
            "script",
            TESTING_A_TEST,
            Some("proof testing_a_test = cleanup;"),
        );
        let (code, report) = c.run_with(Options {
            show_script: true,
            ..Options::default()
        });
        assert_eq!(code, OK, "{}", report);
        assert!(report.contains("derivation — 2 step(s)"), "{}", report);
        assert!(report.contains("bool_result"), "{}", report);
    }
}
